// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as LoginAsServerProcedure from "../login_as_server_procedure";
import * as MatchRoundReplayProcedure from "../match_round_replay_procedure";
import * as NodeLeaderboardInputProcedure from "../node_leaderboard_input_procedure";
import * as NodeLeaderboardInputFinalizeProcedure from "../node_leaderboard_input_finalize_procedure";
import * as NodeLeaderboardOutputProcedure from "../node_leaderboard_output_procedure";
import * as NodeLeaderboardOutputRawProcedure from "../node_leaderboard_output_raw_procedure";
import * as PostRoundReplayProcedure from "../post_round_replay_procedure";
import * as TestNodePermittedPlayersInputProcedure from "../test_node_permitted_players_input_procedure";
import * as UnstableCompetitionProcedure from "../unstable_competition_procedure";
import * as UnstableCompetitionCompetitionsProcedure from "../unstable_competition_competitions_procedure";
import * as UnstableCompetitionConnectionDataProcedure from "../unstable_competition_connection_data_procedure";
import * as UnstableCompetitionInputsProcedure from "../unstable_competition_inputs_procedure";
import * as UnstableCompetitionLeaderboardsProcedure from "../unstable_competition_leaderboards_procedure";
import * as UnstableCompetitionOutputProcedure from "../unstable_competition_output_procedure";
import * as UnstableCompetitionRawServerConfigV2Procedure from "../unstable_competition_raw_server_config_v_2_procedure";

export type LoginAsServerArgs = __Infer<typeof LoginAsServerProcedure.params>;
export type LoginAsServerResult = __Infer<typeof LoginAsServerProcedure.returnType>;
export type MatchRoundReplayArgs = __Infer<typeof MatchRoundReplayProcedure.params>;
export type MatchRoundReplayResult = __Infer<typeof MatchRoundReplayProcedure.returnType>;
export type NodeLeaderboardInputArgs = __Infer<typeof NodeLeaderboardInputProcedure.params>;
export type NodeLeaderboardInputResult = __Infer<typeof NodeLeaderboardInputProcedure.returnType>;
export type NodeLeaderboardInputFinalizeArgs = __Infer<typeof NodeLeaderboardInputFinalizeProcedure.params>;
export type NodeLeaderboardInputFinalizeResult = __Infer<typeof NodeLeaderboardInputFinalizeProcedure.returnType>;
export type NodeLeaderboardOutputArgs = __Infer<typeof NodeLeaderboardOutputProcedure.params>;
export type NodeLeaderboardOutputResult = __Infer<typeof NodeLeaderboardOutputProcedure.returnType>;
export type NodeLeaderboardOutputRawArgs = __Infer<typeof NodeLeaderboardOutputRawProcedure.params>;
export type NodeLeaderboardOutputRawResult = __Infer<typeof NodeLeaderboardOutputRawProcedure.returnType>;
export type PostRoundReplayArgs = __Infer<typeof PostRoundReplayProcedure.params>;
export type PostRoundReplayResult = __Infer<typeof PostRoundReplayProcedure.returnType>;
export type TestNodePermittedPlayersInputArgs = __Infer<typeof TestNodePermittedPlayersInputProcedure.params>;
export type TestNodePermittedPlayersInputResult = __Infer<typeof TestNodePermittedPlayersInputProcedure.returnType>;
export type UnstableCompetitionArgs = __Infer<typeof UnstableCompetitionProcedure.params>;
export type UnstableCompetitionResult = __Infer<typeof UnstableCompetitionProcedure.returnType>;
export type UnstableCompetitionCompetitionsArgs = __Infer<typeof UnstableCompetitionCompetitionsProcedure.params>;
export type UnstableCompetitionCompetitionsResult = __Infer<typeof UnstableCompetitionCompetitionsProcedure.returnType>;
export type UnstableCompetitionConnectionDataArgs = __Infer<typeof UnstableCompetitionConnectionDataProcedure.params>;
export type UnstableCompetitionConnectionDataResult = __Infer<typeof UnstableCompetitionConnectionDataProcedure.returnType>;
export type UnstableCompetitionInputsArgs = __Infer<typeof UnstableCompetitionInputsProcedure.params>;
export type UnstableCompetitionInputsResult = __Infer<typeof UnstableCompetitionInputsProcedure.returnType>;
export type UnstableCompetitionLeaderboardsArgs = __Infer<typeof UnstableCompetitionLeaderboardsProcedure.params>;
export type UnstableCompetitionLeaderboardsResult = __Infer<typeof UnstableCompetitionLeaderboardsProcedure.returnType>;
export type UnstableCompetitionOutputArgs = __Infer<typeof UnstableCompetitionOutputProcedure.params>;
export type UnstableCompetitionOutputResult = __Infer<typeof UnstableCompetitionOutputProcedure.returnType>;
export type UnstableCompetitionRawServerConfigV2Args = __Infer<typeof UnstableCompetitionRawServerConfigV2Procedure.params>;
export type UnstableCompetitionRawServerConfigV2Result = __Infer<typeof UnstableCompetitionRawServerConfigV2Procedure.returnType>;

