// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as LoginAsServerProcedure from "../login_as_server_procedure";
import * as PostRoundReplayProcedure from "../post_round_replay_procedure";

export type LoginAsServerArgs = __Infer<typeof LoginAsServerProcedure.params>;
export type LoginAsServerResult = __Infer<typeof LoginAsServerProcedure.returnType>;
export type PostRoundReplayArgs = __Infer<typeof PostRoundReplayProcedure.params>;
export type PostRoundReplayResult = __Infer<typeof PostRoundReplayProcedure.returnType>;

