// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CompetitionConnectionDataUpdateReducer from "../competition_connection_data_update_reducer";
import CompetitionCreateReducer from "../competition_create_reducer";
import CompetitionEditNameReducer from "../competition_edit_name_reducer";
import CompetitionNodePositionUpdateReducer from "../competition_node_position_update_reducer";
import CompetitionNodePositionsUpdateReducer from "../competition_node_positions_update_reducer";
import CompetitionRegistrationSettingsReducer from "../competition_registration_settings_reducer";
import CreateConnectionReducer from "../create_connection_reducer";
import CreateEnvVarReducer from "../create_env_var_reducer";
import CreateMonitorReducer from "../create_monitor_reducer";
import CreateProjectReducer from "../create_project_reducer";
import CreateScheduleReducer from "../create_schedule_reducer";
import CreateTeamReducer from "../create_team_reducer";
import LendRawServerReducer from "../lend_raw_server_reducer";
import MatchAssignServerReducer from "../match_assign_server_reducer";
import MatchCreateReducer from "../match_create_reducer";
import MatchDeleteReducer from "../match_delete_reducer";
import MatchTemplateCreateReducer from "../match_template_create_reducer";
import MatchTryStartReducer from "../match_try_start_reducer";
import MatchUpdateConfigReducer from "../match_update_config_reducer";
import MatchUpdatePreConfigReducer from "../match_update_pre_config_reducer";
import PortalCreateReducer from "../portal_create_reducer";
import PostEventReducer from "../post_event_reducer";
import PostRecordReducer from "../post_record_reducer";
import ProjectEditDatesReducer from "../project_edit_dates_reducer";
import ProjectEditDescriptionReducer from "../project_edit_description_reducer";
import ProjectEditNameReducer from "../project_edit_name_reducer";
import ProjectMemberAddReducer from "../project_member_add_reducer";
import ProjectMemberAssignPermissionReducer from "../project_member_assign_permission_reducer";
import ProjectMemberRemoveReducer from "../project_member_remove_reducer";
import ProjectRoleAssignPermissionReducer from "../project_role_assign_permission_reducer";
import ProjectRoleCreateReducer from "../project_role_create_reducer";
import ProjectRoleMemberAssignReducer from "../project_role_member_assign_reducer";
import ProjectRoleMemberRemoveReducer from "../project_role_member_remove_reducer";
import ProjectRoleRemoveReducer from "../project_role_remove_reducer";
import ProjectUpdateStatusReducer from "../project_update_status_reducer";
import RawServerPlayerAddReducer from "../raw_server_player_add_reducer";
import RawServerPlayerRemoveReducer from "../raw_server_player_remove_reducer";
import RawServerVerifyReducer from "../raw_server_verify_reducer";
import RegisterPlayerReducer from "../register_player_reducer";
import RevokeRawServerReducer from "../revoke_raw_server_reducer";
import ServerMethodCallReducer from "../server_method_call_reducer";
import ServerMethodResponseReducer from "../server_method_response_reducer";
import UnregisterPlayerReducer from "../unregister_player_reducer";

export type CompetitionConnectionDataUpdateParams = __Infer<typeof CompetitionConnectionDataUpdateReducer>;
export type CompetitionCreateParams = __Infer<typeof CompetitionCreateReducer>;
export type CompetitionEditNameParams = __Infer<typeof CompetitionEditNameReducer>;
export type CompetitionNodePositionUpdateParams = __Infer<typeof CompetitionNodePositionUpdateReducer>;
export type CompetitionNodePositionsUpdateParams = __Infer<typeof CompetitionNodePositionsUpdateReducer>;
export type CompetitionRegistrationSettingsParams = __Infer<typeof CompetitionRegistrationSettingsReducer>;
export type CreateConnectionParams = __Infer<typeof CreateConnectionReducer>;
export type CreateEnvVarParams = __Infer<typeof CreateEnvVarReducer>;
export type CreateMonitorParams = __Infer<typeof CreateMonitorReducer>;
export type CreateProjectParams = __Infer<typeof CreateProjectReducer>;
export type CreateScheduleParams = __Infer<typeof CreateScheduleReducer>;
export type CreateTeamParams = __Infer<typeof CreateTeamReducer>;
export type LendRawServerParams = __Infer<typeof LendRawServerReducer>;
export type MatchAssignServerParams = __Infer<typeof MatchAssignServerReducer>;
export type MatchCreateParams = __Infer<typeof MatchCreateReducer>;
export type MatchDeleteParams = __Infer<typeof MatchDeleteReducer>;
export type MatchTemplateCreateParams = __Infer<typeof MatchTemplateCreateReducer>;
export type MatchTryStartParams = __Infer<typeof MatchTryStartReducer>;
export type MatchUpdateConfigParams = __Infer<typeof MatchUpdateConfigReducer>;
export type MatchUpdatePreConfigParams = __Infer<typeof MatchUpdatePreConfigReducer>;
export type PortalCreateParams = __Infer<typeof PortalCreateReducer>;
export type PostEventParams = __Infer<typeof PostEventReducer>;
export type PostRecordParams = __Infer<typeof PostRecordReducer>;
export type ProjectEditDatesParams = __Infer<typeof ProjectEditDatesReducer>;
export type ProjectEditDescriptionParams = __Infer<typeof ProjectEditDescriptionReducer>;
export type ProjectEditNameParams = __Infer<typeof ProjectEditNameReducer>;
export type ProjectMemberAddParams = __Infer<typeof ProjectMemberAddReducer>;
export type ProjectMemberAssignPermissionParams = __Infer<typeof ProjectMemberAssignPermissionReducer>;
export type ProjectMemberRemoveParams = __Infer<typeof ProjectMemberRemoveReducer>;
export type ProjectRoleAssignPermissionParams = __Infer<typeof ProjectRoleAssignPermissionReducer>;
export type ProjectRoleCreateParams = __Infer<typeof ProjectRoleCreateReducer>;
export type ProjectRoleMemberAssignParams = __Infer<typeof ProjectRoleMemberAssignReducer>;
export type ProjectRoleMemberRemoveParams = __Infer<typeof ProjectRoleMemberRemoveReducer>;
export type ProjectRoleRemoveParams = __Infer<typeof ProjectRoleRemoveReducer>;
export type ProjectUpdateStatusParams = __Infer<typeof ProjectUpdateStatusReducer>;
export type RawServerPlayerAddParams = __Infer<typeof RawServerPlayerAddReducer>;
export type RawServerPlayerRemoveParams = __Infer<typeof RawServerPlayerRemoveReducer>;
export type RawServerVerifyParams = __Infer<typeof RawServerVerifyReducer>;
export type RegisterPlayerParams = __Infer<typeof RegisterPlayerReducer>;
export type RevokeRawServerParams = __Infer<typeof RevokeRawServerReducer>;
export type ServerMethodCallParams = __Infer<typeof ServerMethodCallReducer>;
export type ServerMethodResponseParams = __Infer<typeof ServerMethodResponseReducer>;
export type UnregisterPlayerParams = __Infer<typeof UnregisterPlayerReducer>;

