// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import RespawnBehaviour from "./respawn_behaviour_type";
import WarmupDuration from "./warmup_duration_type";
import WarmupTimeout from "./warmup_timeout_type";


export default __t.object("Common", {
  chatTime: __t.u32(),
  get respawnBehaviour() {
    return RespawnBehaviour;
  },
  delayBeforeNextMap: __t.u32(),
  synchronizePlayersAtMapStart: __t.bool(),
  synchronizePlayersAtRoundStart: __t.bool(),
  trustClientSimulation: __t.bool(),
  useCrudeExtrapolation: __t.bool(),
  get warmupDuration() {
    return WarmupDuration;
  },
  get warmupTimeout() {
    return WarmupTimeout;
  },
  warmupNumber: __t.u32(),
  decoImageUrlCheckpoint: __t.string(),
  decoImageUrlDecalSponsor4X1: __t.string(),
  decoImageUrlScreen16X1: __t.string(),
  decoImageUrlScreen16X9: __t.string(),
  decoImageUrlScreen8X1: __t.string(),
  decoImageUrlWhoAmIUrl: __t.string(),
  forceLapsNumber: __t.i32(),
});


