// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import NodeKindRef from "./node_kind_ref_type";
import ConnectionSettings from "./connection_settings_type";


export default __t.row({
  competitionId: __t.u32().name("competition_id"),
  get connectionFrom() {
    return NodeKindRef.name("connection_from");
  },
  get connectionTo() {
    return NodeKindRef.name("connection_to");
  },
  get connectionSettings() {
    return ConnectionSettings.name("connection_settings");
  },
});
