// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  mapUid: __t.string().name("map_uid"),
  accountId: __t.uuid().name("account_id"),
  timestamp: __t.timestamp(),
  time: __t.u32(),
  zone: __t.string(),
  playerName: __t.string().name("player_name"),
  ghost: __t.string(),
});
