// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import NodeKindRef from "./node_kind_ref_type";
import ConnectionSettings from "./connection_settings_type";


export default __t.object("CompetitionConnection", {
  tournamentId: __t.u32(),
  competitionId: __t.u32(),
  get connectionFrom() {
    return NodeKindRef;
  },
  get connectionTo() {
    return NodeKindRef;
  },
  get connectionSettings() {
    return ConnectionSettings;
  },
});


