// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import CompetitionStatus from "./competition_status_type";
import RegistrationSettings from "./registration_settings_type";


export default __t.object("CompetitionV1", {
  id: __t.u32(),
  tournamentId: __t.u32(),
  parentId: __t.option(__t.u32()),
  name: __t.string(),
  get status() {
    return CompetitionStatus;
  },
  startingAt: __t.option(__t.timestamp()),
  endingAt: __t.option(__t.timestamp()),
  get registrationSettings() {
    return RegistrationSettings;
  },
});


