// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  competitionId: __t.u32().name("competition_id"),
  connectionId: __t.u32().name("connection_id"),
  countTop: __t.option(__t.u8()).name("count_top"),
  countBottom: __t.option(__t.u8()).name("count_bottom"),
  customList: __t.byteArray().name("custom_list"),
});
