// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import NodeKindHandle from "./node_kind_handle_type";
import Vec2 from "./vec_2_type";


export default __t.object("CompetitionNodePosition", {
  competitionId: __t.u32(),
  get node() {
    return NodeKindHandle;
  },
  get position() {
    return Vec2;
  },
});


