// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  NodeKindHandle,
  ConnectionSettings,
} from "./types";

export default {
  get connectionFrom() {
    return NodeKindHandle;
  },
  get connectionTo() {
    return NodeKindHandle;
  },
  get setting() {
    return ConnectionSettings;
  },
};
