// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.11.1 (commit bbfa851b45db7096aa2a69d7dbad84f52983559f).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  convertToAccessorMap as __convertToAccessorMap,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import and reexport all reducer arg types
import AddDependencyReducer from "./add_dependency_reducer";
export { AddDependencyReducer };
import ClientConnectedReducer from "./client_connected_reducer";
export { ClientConnectedReducer };
import CompetitionRegisterPlayerReducer from "./competition_register_player_reducer";
export { CompetitionRegisterPlayerReducer };
import CompetitionUnregisterPlayerReducer from "./competition_unregister_player_reducer";
export { CompetitionUnregisterPlayerReducer };
import CreateCompetitionReducer from "./create_competition_reducer";
export { CreateCompetitionReducer };
import CreateEnvVarReducer from "./create_env_var_reducer";
export { CreateEnvVarReducer };
import CreateEventTemplateReducer from "./create_event_template_reducer";
export { CreateEventTemplateReducer };
import CreateMatchReducer from "./create_match_reducer";
export { CreateMatchReducer };
import CreateMonitorReducer from "./create_monitor_reducer";
export { CreateMonitorReducer };
import CreateServerConfigReducer from "./create_server_config_reducer";
export { CreateServerConfigReducer };
import CreateTournamentReducer from "./create_tournament_reducer";
export { CreateTournamentReducer };
import IdentityDisconnectedReducer from "./identity_disconnected_reducer";
export { IdentityDisconnectedReducer };
import MatchAssignServerReducer from "./match_assign_server_reducer";
export { MatchAssignServerReducer };
import MatchConfiguredReducer from "./match_configured_reducer";
export { MatchConfiguredReducer };
import OnTournamentEventScheduleReducer from "./on_tournament_event_schedule_reducer";
export { OnTournamentEventScheduleReducer };
import PostEventReducer from "./post_event_reducer";
export { PostEventReducer };
import PostRecordReducer from "./post_record_reducer";
export { PostRecordReducer };
import ServerMethodCallReducer from "./server_method_call_reducer";
export { ServerMethodCallReducer };
import ServerMethodResponseReducer from "./server_method_response_reducer";
export { ServerMethodResponseReducer };
import TryStartMatchReducer from "./try_start_match_reducer";
export { TryStartMatchReducer };
import UpdateMatchConfigReducer from "./update_match_config_reducer";
export { UpdateMatchConfigReducer };
import UpdatePreMatchConfigReducer from "./update_pre_match_config_reducer";
export { UpdatePreMatchConfigReducer };

// Import and reexport all procedure arg types
import * as LoginAsServerProcedure from "./login_as_server_procedure";
export { LoginAsServerProcedure };
import * as LoginAsWorkerProcedure from "./login_as_worker_procedure";
export { LoginAsWorkerProcedure };
import * as PostRoundReplayProcedure from "./post_round_replay_procedure";
export { PostRoundReplayProcedure };

// Import and reexport all table handle types
import CompetitionRow from "./competition_table";
export { CompetitionRow };
import CompetitionRecordRow from "./competition_record_table";
export { CompetitionRecordRow };
import CompetitionScheduleRow from "./competition_schedule_table";
export { CompetitionScheduleRow };
import EnvRow from "./env_table";
export { EnvRow };
import EventConfigRow from "./event_config_table";
export { EventConfigRow };
import GeneratorRow from "./generator_table";
export { GeneratorRow };
import MapRecordRow from "./map_record_table";
export { MapRecordRow };
import MatchEventRow from "./match_event_table";
export { MatchEventRow };
import MatchGhostRow from "./match_ghost_table";
export { MatchGhostRow };
import MatchRecordRow from "./match_record_table";
export { MatchRecordRow };
import MatchStandingsRow from "./match_standings_table";
export { MatchStandingsRow };
import MatchTemplateRow from "./match_template_table";
export { MatchTemplateRow };
import MyJobsRow from "./my_jobs_table";
export { MyJobsRow };
import MyTournamentRow from "./my_tournament_table";
export { MyTournamentRow };
import RegistrationPlayerRow from "./registration_player_table";
export { RegistrationPlayerRow };
import TabTournamentRow from "./tab_tournament_table";
export { TabTournamentRow };
import ThisTmServerRow from "./this_tm_server_table";
export { ThisTmServerRow };
import TmMapRecordRow from "./tm_map_record_table";
export { TmMapRecordRow };
import TmMatchRow from "./tm_match_table";
export { TmMatchRow };
import TmMatchRecordRow from "./tm_match_record_table";
export { TmMatchRecordRow };
import TmMonitoringRow from "./tm_monitoring_table";
export { TmMonitoringRow };
import TmServerRow from "./tm_server_table";
export { TmServerRow };
import TmServerConfigRow from "./tm_server_config_table";
export { TmServerConfigRow };
import TmServerMethodCallRow from "./tm_server_method_call_table";
export { TmServerMethodCallRow };
import TmServerMethodResponseRow from "./tm_server_method_response_table";
export { TmServerMethodResponseRow };
import TmWorkerRow from "./tm_worker_table";
export { TmWorkerRow };
import TmWorkerJobsRow from "./tm_worker_jobs_table";
export { TmWorkerJobsRow };
import TournamentRow from "./tournament_table";
export { TournamentRow };
import UserRow from "./user_table";
export { UserRow };
import UserIdentityRow from "./user_identity_table";
export { UserIdentityRow };

// Import and reexport all types
import BanArgs from "./ban_args_type";
export { BanArgs };
import ChatSendServerMessageToUserArgs from "./chat_send_server_message_to_user_args_type";
export { ChatSendServerMessageToUserArgs };
import ChatSendToUserArgs from "./chat_send_to_user_args_type";
export { ChatSendToUserArgs };
import Common from "./common_type";
export { Common };
import Competition from "./competition_type";
export { Competition };
import CompetitionKind from "./competition_kind_type";
export { CompetitionKind };
import CompetitionSchedule from "./competition_schedule_type";
export { CompetitionSchedule };
import CompetitionStatus from "./competition_status_type";
export { CompetitionStatus };
import Competitions from "./competitions_type";
export { Competitions };
import Custom from "./custom_type";
export { Custom };
import Edge from "./edge_type";
export { Edge };
import EndMapEnd from "./end_map_end_type";
export { EndMapEnd };
import EndMapStart from "./end_map_start_type";
export { EndMapStart };
import EndMatch from "./end_match_type";
export { EndMatch };
import EndRoundEnd from "./end_round_end_type";
export { EndRoundEnd };
import EndRoundStart from "./end_round_start_type";
export { EndRoundStart };
import EndServer from "./end_server_type";
export { EndServer };
import EndTurnEnd from "./end_turn_end_type";
export { EndTurnEnd };
import EndTurnStart from "./end_turn_start_type";
export { EndTurnStart };
import Env from "./env_type";
export { Env };
import Event from "./event_type";
export { Event };
import EventConfig from "./event_config_type";
export { EventConfig };
import Generator from "./generator_type";
export { Generator };
import GiveUp from "./give_up_type";
export { GiveUp };
import KickArgs from "./kick_args_type";
export { KickArgs };
import LoadingMapEnd from "./loading_map_end_type";
export { LoadingMapEnd };
import LoadingMapStart from "./loading_map_start_type";
export { LoadingMapStart };
import Map from "./map_type";
export { Map };
import MapPoolConfig from "./map_pool_config_type";
export { MapPoolConfig };
import MatchEntityRules from "./match_entity_rules_type";
export { MatchEntityRules };
import MatchEvent from "./match_event_type";
export { MatchEvent };
import MatchGhost from "./match_ghost_type";
export { MatchGhost };
import MatchLeaderboardRules from "./match_leaderboard_rules_type";
export { MatchLeaderboardRules };
import MatchStandings from "./match_standings_type";
export { MatchStandings };
import MatchState from "./match_state_type";
export { MatchState };
import MatchStatus from "./match_status_type";
export { MatchStatus };
import MatchTemplate from "./match_template_type";
export { MatchTemplate };
import MethodCall from "./method_call_type";
export { MethodCall };
import MethodError from "./method_error_type";
export { MethodError };
import MethodResponse from "./method_response_type";
export { MethodResponse };
import ModeConfig from "./mode_config_type";
export { ModeConfig };
import ModeRules from "./mode_rules_type";
export { ModeRules };
import MonitoringSettings from "./monitoring_settings_type";
export { MonitoringSettings };
import MonitoringSettingsClub from "./monitoring_settings_club_type";
export { MonitoringSettingsClub };
import MonitoringSettingsMap from "./monitoring_settings_map_type";
export { MonitoringSettingsMap };
import Node from "./node_type";
export { Node };
import PlayLoopEnd from "./play_loop_end_type";
export { PlayLoopEnd };
import PlayLoopStart from "./play_loop_start_type";
export { PlayLoopStart };
import Player from "./player_type";
export { Player };
import PlayerChat from "./player_chat_type";
export { PlayerChat };
import PlayerConnect from "./player_connect_type";
export { PlayerConnect };
import PlayerDisconnect from "./player_disconnect_type";
export { PlayerDisconnect };
import Podium from "./podium_type";
export { Podium };
import RegistrationPlayer from "./registration_player_type";
export { RegistrationPlayer };
import RegistrationPlayerRules from "./registration_player_rules_type";
export { RegistrationPlayerRules };
import RegistrationRules from "./registration_rules_type";
export { RegistrationRules };
import RegistrationTeamRules from "./registration_team_rules_type";
export { RegistrationTeamRules };
import Respawn from "./respawn_type";
export { Respawn };
import RespawnBavaviour from "./respawn_bavaviour_type";
export { RespawnBavaviour };
import RoundTime from "./round_time_type";
export { RoundTime };
import Rounds from "./rounds_type";
export { Rounds };
import RoundsLeaderboard from "./rounds_leaderboard_type";
export { RoundsLeaderboard };
import Scheduling from "./scheduling_type";
export { Scheduling };
import Scores from "./scores_type";
export { Scores };
import ServerConfig from "./server_config_type";
export { ServerConfig };
import ServerOptions from "./server_options_type";
export { ServerOptions };
import ServerState from "./server_state_type";
export { ServerState };
import StartEnd from "./start_end_type";
export { StartEnd };
import StartLine from "./start_line_type";
export { StartLine };
import StartMap from "./start_map_type";
export { StartMap };
import StartMatch from "./start_match_type";
export { StartMatch };
import StartRound from "./start_round_type";
export { StartRound };
import StartServer from "./start_server_type";
export { StartServer };
import StartTurn from "./start_turn_type";
export { StartTurn };
import Team from "./team_type";
export { Team };
import TmCompRecord from "./tm_comp_record_type";
export { TmCompRecord };
import TmMapRecord from "./tm_map_record_type";
export { TmMapRecord };
import TmMatch from "./tm_match_type";
export { TmMatch };
import TmMonitoring from "./tm_monitoring_type";
export { TmMonitoring };
import TmRecord from "./tm_record_type";
export { TmRecord };
import TmServer from "./tm_server_type";
export { TmServer };
import TmServerConfig from "./tm_server_config_type";
export { TmServerConfig };
import TmServerMethodCall from "./tm_server_method_call_type";
export { TmServerMethodCall };
import TmServerMethodResponse from "./tm_server_method_response_type";
export { TmServerMethodResponse };
import TmWorker from "./tm_worker_type";
export { TmWorker };
import TmWorkerJobs from "./tm_worker_jobs_type";
export { TmWorkerJobs };
import TournamentStatus from "./tournament_status_type";
export { TournamentStatus };
import TournamentV1 from "./tournament_v_1_type";
export { TournamentV1 };
import UnloadingMapEnd from "./unloading_map_end_type";
export { UnloadingMapEnd };
import UnloadingMapStart from "./unloading_map_start_type";
export { UnloadingMapStart };
import User from "./user_type";
export { User };
import UserIdentity from "./user_identity_type";
export { UserIdentity };
import WarmupDuration from "./warmup_duration_type";
export { WarmupDuration };
import WarmupRound from "./warmup_round_type";
export { WarmupRound };
import WayPoint from "./way_point_type";
export { WayPoint };

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema(
  __table({
    name: 'competition',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'competition_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CompetitionRow),
  __table({
    name: 'competition_schedule',
    indexes: [
      { name: 'scheduled_id', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'competition_schedule_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, CompetitionScheduleRow),
  __table({
    name: 'env',
    indexes: [
      { name: 'key', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'env_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, EnvRow),
  __table({
    name: 'event_config',
    indexes: [
    ],
    constraints: [
    ],
  }, EventConfigRow),
  __table({
    name: 'generator',
    indexes: [
    ],
    constraints: [
    ],
  }, GeneratorRow),
  __table({
    name: 'match_event',
    indexes: [
      { name: 'event', algorithm: 'btree', columns: [
        'event',
      ] },
      { name: 'event_match', algorithm: 'btree', columns: [
        'matchId',
      ] },
    ],
    constraints: [
    ],
  }, MatchEventRow),
  __table({
    name: 'match_ghost',
    indexes: [
    ],
    constraints: [
    ],
  }, MatchGhostRow),
  __table({
    name: 'match_template',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'match_template_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MatchTemplateRow),
  __table({
    name: 'registration_player',
    indexes: [
    ],
    constraints: [
    ],
  }, RegistrationPlayerRow),
  __table({
    name: 'tab_tournament',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'name', algorithm: 'btree', columns: [
        'name',
      ] },
    ],
    constraints: [
      { name: 'tab_tournament_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'tab_tournament_name_key', constraint: 'unique', columns: ['name'] },
    ],
  }, TabTournamentRow),
  __table({
    name: 'tm_map_record',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'record_id', algorithm: 'btree', columns: [
        'mapUid',
        'playerUid',
      ] },
    ],
    constraints: [
      { name: 'tm_map_record_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TmMapRecordRow),
  __table({
    name: 'tm_match',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'tm_match_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TmMatchRow),
  __table({
    name: 'tm_match_record',
    indexes: [
      { name: 'record_id', algorithm: 'btree', columns: [
        'matchId',
        'mapUid',
        'playerUid',
      ] },
    ],
    constraints: [
    ],
  }, TmMatchRecordRow),
  __table({
    name: 'tm_monitoring',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'tm_monitoring_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TmMonitoringRow),
  __table({
    name: 'tm_server',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
      { name: 'tm_login', algorithm: 'btree', columns: [
        'tmLogin',
      ] },
    ],
    constraints: [
      { name: 'tm_server_identity_key', constraint: 'unique', columns: ['identity'] },
      { name: 'tm_server_tm_login_key', constraint: 'unique', columns: ['tmLogin'] },
    ],
  }, TmServerRow),
  __table({
    name: 'tm_server_config',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'tm_server_config_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TmServerConfigRow),
  __table({
    name: 'tm_server_method_call',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'tm_server_method_call_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TmServerMethodCallRow),
  __table({
    name: 'tm_server_method_response',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'tm_server_method_response_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TmServerMethodResponseRow),
  __table({
    name: 'tm_worker',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
      { name: 'tm_login', algorithm: 'btree', columns: [
        'tmLogin',
      ] },
    ],
    constraints: [
      { name: 'tm_worker_identity_key', constraint: 'unique', columns: ['identity'] },
      { name: 'tm_worker_tm_login_key', constraint: 'unique', columns: ['tmLogin'] },
    ],
  }, TmWorkerRow),
  __table({
    name: 'tm_worker_jobs',
    indexes: [
      { name: 'worker_id', algorithm: 'btree', columns: [
        'tmLogin',
      ] },
    ],
    constraints: [
    ],
  }, TmWorkerJobsRow),
  __table({
    name: 'user',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'user_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, UserRow),
  __table({
    name: 'user_identity',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'user_identity_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, UserIdentityRow),
  __table({
    name: 'competition_record',
    indexes: [
    ],
    constraints: [
    ],
  }, CompetitionRecordRow),
  __table({
    name: 'map_record',
    indexes: [
    ],
    constraints: [
    ],
  }, MapRecordRow),
  __table({
    name: 'match_record',
    indexes: [
    ],
    constraints: [
    ],
  }, MatchRecordRow),
  __table({
    name: 'match_standings',
    indexes: [
    ],
    constraints: [
    ],
  }, MatchStandingsRow),
  __table({
    name: 'my_jobs',
    indexes: [
    ],
    constraints: [
    ],
  }, MyJobsRow),
  __table({
    name: 'my_tournament',
    indexes: [
    ],
    constraints: [
    ],
  }, MyTournamentRow),
  __table({
    name: 'this_tm_server',
    indexes: [
    ],
    constraints: [
    ],
  }, ThisTmServerRow),
  __table({
    name: 'tournament',
    indexes: [
    ],
    constraints: [
    ],
  }, TournamentRow),
);

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("add_dependency", AddDependencyReducer),
  __reducerSchema("competition_register_player", CompetitionRegisterPlayerReducer),
  __reducerSchema("competition_unregister_player", CompetitionUnregisterPlayerReducer),
  __reducerSchema("create_competition", CreateCompetitionReducer),
  __reducerSchema("create_env_var", CreateEnvVarReducer),
  __reducerSchema("create_event_template", CreateEventTemplateReducer),
  __reducerSchema("create_match", CreateMatchReducer),
  __reducerSchema("create_monitor", CreateMonitorReducer),
  __reducerSchema("create_server_config", CreateServerConfigReducer),
  __reducerSchema("create_tournament", CreateTournamentReducer),
  __reducerSchema("match_assign_server", MatchAssignServerReducer),
  __reducerSchema("match_configured", MatchConfiguredReducer),
  __reducerSchema("on_tournament_event_schedule", OnTournamentEventScheduleReducer),
  __reducerSchema("post_event", PostEventReducer),
  __reducerSchema("post_record", PostRecordReducer),
  __reducerSchema("server_method_call", ServerMethodCallReducer),
  __reducerSchema("server_method_response", ServerMethodResponseReducer),
  __reducerSchema("try_start_match", TryStartMatchReducer),
  __reducerSchema("update_match_config", UpdateMatchConfigReducer),
  __reducerSchema("update_pre_match_config", UpdatePreMatchConfigReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
  __procedureSchema("login_as_server", LoginAsServerProcedure.params, LoginAsServerProcedure.returnType),
  __procedureSchema("login_as_worker", LoginAsWorkerProcedure.params, LoginAsWorkerProcedure.returnType),
  __procedureSchema("post_round_replay", PostRoundReplayProcedure.params, PostRoundReplayProcedure.returnType),
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "1.11.1" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. */
export const tables = __convertToAccessorMap(tablesSchema.schemaType.tables);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

