// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.11.1 (commit bbfa851b45db7096aa2a69d7dbad84f52983559f).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  convertToAccessorMap as __convertToAccessorMap,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import and reexport all reducer arg types
import ClientConnectedReducer from "./client_connected_reducer";
export { ClientConnectedReducer };
import ClientDisconnectedReducer from "./client_disconnected_reducer";
export { ClientDisconnectedReducer };
import CompetitionEditNameReducer from "./competition_edit_name_reducer";
export { CompetitionEditNameReducer };
import CompetitionRegistrationSettingsReducer from "./competition_registration_settings_reducer";
export { CompetitionRegistrationSettingsReducer };
import CreateCompetitionReducer from "./create_competition_reducer";
export { CreateCompetitionReducer };
import CreateConnectionReducer from "./create_connection_reducer";
export { CreateConnectionReducer };
import CreateEnvVarReducer from "./create_env_var_reducer";
export { CreateEnvVarReducer };
import CreateEventTemplateReducer from "./create_event_template_reducer";
export { CreateEventTemplateReducer };
import CreateMatchReducer from "./create_match_reducer";
export { CreateMatchReducer };
import CreateMatchTemplateReducer from "./create_match_template_reducer";
export { CreateMatchTemplateReducer };
import CreateMonitorReducer from "./create_monitor_reducer";
export { CreateMonitorReducer };
import CreateScheduleReducer from "./create_schedule_reducer";
export { CreateScheduleReducer };
import CreateServerConfigReducer from "./create_server_config_reducer";
export { CreateServerConfigReducer };
import CreateTeamReducer from "./create_team_reducer";
export { CreateTeamReducer };
import CreateTournamentReducer from "./create_tournament_reducer";
export { CreateTournamentReducer };
import InternalGraphResolutionNodeFinishedReducer from "./internal_graph_resolution_node_finished_reducer";
export { InternalGraphResolutionNodeFinishedReducer };
import MatchAssignServerReducer from "./match_assign_server_reducer";
export { MatchAssignServerReducer };
import MatchConfiguredReducer from "./match_configured_reducer";
export { MatchConfiguredReducer };
import OnScheduleTriggeredReducer from "./on_schedule_triggered_reducer";
export { OnScheduleTriggeredReducer };
import OnTournamentStatusScheduleTriggeredReducer from "./on_tournament_status_schedule_triggered_reducer";
export { OnTournamentStatusScheduleTriggeredReducer };
import PostEventReducer from "./post_event_reducer";
export { PostEventReducer };
import PostRecordReducer from "./post_record_reducer";
export { PostRecordReducer };
import RegisterPlayerReducer from "./register_player_reducer";
export { RegisterPlayerReducer };
import ServerMethodCallReducer from "./server_method_call_reducer";
export { ServerMethodCallReducer };
import ServerMethodResponseReducer from "./server_method_response_reducer";
export { ServerMethodResponseReducer };
import TournamentEditDatesReducer from "./tournament_edit_dates_reducer";
export { TournamentEditDatesReducer };
import TournamentEditDescriptionReducer from "./tournament_edit_description_reducer";
export { TournamentEditDescriptionReducer };
import TournamentEditNameReducer from "./tournament_edit_name_reducer";
export { TournamentEditNameReducer };
import TournamentUpdateStatusReducer from "./tournament_update_status_reducer";
export { TournamentUpdateStatusReducer };
import TryStartMatchReducer from "./try_start_match_reducer";
export { TryStartMatchReducer };
import UnregisterPlayerReducer from "./unregister_player_reducer";
export { UnregisterPlayerReducer };
import UpdateMatchConfigReducer from "./update_match_config_reducer";
export { UpdateMatchConfigReducer };
import UpdatePreMatchConfigReducer from "./update_pre_match_config_reducer";
export { UpdatePreMatchConfigReducer };

// Import and reexport all procedure arg types
import * as LoginAsServerProcedure from "./login_as_server_procedure";
export { LoginAsServerProcedure };
import * as LoginAsWorkerProcedure from "./login_as_worker_procedure";
export { LoginAsWorkerProcedure };
import * as PostRoundReplayProcedure from "./post_round_replay_procedure";
export { PostRoundReplayProcedure };

// Import and reexport all table handle types
import CompetitionRow from "./competition_table";
export { CompetitionRow };
import CompetitionConnectionRow from "./competition_connection_table";
export { CompetitionConnectionRow };
import CompetitionRecordRow from "./competition_record_table";
export { CompetitionRecordRow };
import EnvRow from "./env_table";
export { EnvRow };
import GeneratorRow from "./generator_table";
export { GeneratorRow };
import MapRecordRow from "./map_record_table";
export { MapRecordRow };
import MatchGhostRow from "./match_ghost_table";
export { MatchGhostRow };
import MatchLeaderbaordRow from "./match_leaderbaord_table";
export { MatchLeaderbaordRow };
import MatchPlayersRow from "./match_players_table";
export { MatchPlayersRow };
import MatchRecordRow from "./match_record_table";
export { MatchRecordRow };
import MatchRoundRow from "./match_round_table";
export { MatchRoundRow };
import MatchTemplateRow from "./match_template_table";
export { MatchTemplateRow };
import MyJobsRow from "./my_jobs_table";
export { MyJobsRow };
import MyMatchTemplateRow from "./my_match_template_table";
export { MyMatchTemplateRow };
import MyTournamentRow from "./my_tournament_table";
export { MyTournamentRow };
import RawServerRow from "./raw_server_table";
export { RawServerRow };
import RawServerCurrentPlayersRow from "./raw_server_current_players_table";
export { RawServerCurrentPlayersRow };
import RawServerExpectedPlayersRow from "./raw_server_expected_players_table";
export { RawServerExpectedPlayersRow };
import RegisteredPlayerRow from "./registered_player_table";
export { RegisteredPlayerRow };
import ScheduleRow from "./schedule_table";
export { ScheduleRow };
import TabCompetitionRow from "./tab_competition_table";
export { TabCompetitionRow };
import TabCompetitionConnectionRow from "./tab_competition_connection_table";
export { TabCompetitionConnectionRow };
import TabRawServerOfflineRow from "./tab_raw_server_offline_table";
export { TabRawServerOfflineRow };
import TabRawServerOnlineRow from "./tab_raw_server_online_table";
export { TabRawServerOnlineRow };
import TabRegisteredPlayerRow from "./tab_registered_player_table";
export { TabRegisteredPlayerRow };
import TabRegisteredTeamRow from "./tab_registered_team_table";
export { TabRegisteredTeamRow };
import TabScheduleRow from "./tab_schedule_table";
export { TabScheduleRow };
import TabTmMatchRow from "./tab_tm_match_table";
export { TabTmMatchRow };
import TabTmMatchEventRow from "./tab_tm_match_event_table";
export { TabTmMatchEventRow };
import TabTmMatchPlayersRow from "./tab_tm_match_players_table";
export { TabTmMatchPlayersRow };
import TabTmMatchSpectatorsRow from "./tab_tm_match_spectators_table";
export { TabTmMatchSpectatorsRow };
import TabTmMatchStateRow from "./tab_tm_match_state_table";
export { TabTmMatchStateRow };
import TabTournamentRow from "./tab_tournament_table";
export { TabTournamentRow };
import TabTournamentStatusScheduleRow from "./tab_tournament_status_schedule_table";
export { TabTournamentStatusScheduleRow };
import TabUserRow from "./tab_user_table";
export { TabUserRow };
import ThisRawServerRow from "./this_raw_server_table";
export { ThisRawServerRow };
import TmMapRecordRow from "./tm_map_record_table";
export { TmMapRecordRow };
import TmMatchRow from "./tm_match_table";
export { TmMatchRow };
import TmMatchRecordRow from "./tm_match_record_table";
export { TmMatchRecordRow };
import TmMonitoringRow from "./tm_monitoring_table";
export { TmMonitoringRow };
import TmServerConfigRow from "./tm_server_config_table";
export { TmServerConfigRow };
import TmServerMethodCallRow from "./tm_server_method_call_table";
export { TmServerMethodCallRow };
import TmServerMethodResponseRow from "./tm_server_method_response_table";
export { TmServerMethodResponseRow };
import TmWorkerRow from "./tm_worker_table";
export { TmWorkerRow };
import TmWorkerJobsRow from "./tm_worker_jobs_table";
export { TmWorkerJobsRow };
import TournamentRow from "./tournament_table";
export { TournamentRow };
import UserRow from "./user_table";
export { UserRow };
import UserIdentityRow from "./user_identity_table";
export { UserIdentityRow };

// Import and reexport all types
import BanArgs from "./ban_args_type";
export { BanArgs };
import ChatSendServerMessageToUserArgs from "./chat_send_server_message_to_user_args_type";
export { ChatSendServerMessageToUserArgs };
import ChatSendToUserArgs from "./chat_send_to_user_args_type";
export { ChatSendToUserArgs };
import Common from "./common_type";
export { Common };
import CompetitionConnection from "./competition_connection_type";
export { CompetitionConnection };
import CompetitionStatus from "./competition_status_type";
export { CompetitionStatus };
import CompetitionV1 from "./competition_v_1_type";
export { CompetitionV1 };
import ConnectionSettings from "./connection_settings_type";
export { ConnectionSettings };
import Custom from "./custom_type";
export { Custom };
import EndMapEnd from "./end_map_end_type";
export { EndMapEnd };
import EndMapStart from "./end_map_start_type";
export { EndMapStart };
import EndMatch from "./end_match_type";
export { EndMatch };
import EndRoundEnd from "./end_round_end_type";
export { EndRoundEnd };
import EndRoundStart from "./end_round_start_type";
export { EndRoundStart };
import EndServer from "./end_server_type";
export { EndServer };
import EndTurnEnd from "./end_turn_end_type";
export { EndTurnEnd };
import EndTurnStart from "./end_turn_start_type";
export { EndTurnStart };
import Env from "./env_type";
export { Env };
import Event from "./event_type";
export { Event };
import FinishTimeout from "./finish_timeout_type";
export { FinishTimeout };
import Generator from "./generator_type";
export { Generator };
import GiveUp from "./give_up_type";
export { GiveUp };
import KickArgs from "./kick_args_type";
export { KickArgs };
import LeaderboardEntry from "./leaderboard_entry_type";
export { LeaderboardEntry };
import LoadingMapEnd from "./loading_map_end_type";
export { LoadingMapEnd };
import LoadingMapStart from "./loading_map_start_type";
export { LoadingMapStart };
import Map from "./map_type";
export { Map };
import MapPoolConfig from "./map_pool_config_type";
export { MapPoolConfig };
import MatchGhost from "./match_ghost_type";
export { MatchGhost };
import MatchStatus from "./match_status_type";
export { MatchStatus };
import MatchTemplate from "./match_template_type";
export { MatchTemplate };
import MethodCall from "./method_call_type";
export { MethodCall };
import MethodError from "./method_error_type";
export { MethodError };
import MethodResponse from "./method_response_type";
export { MethodResponse };
import ModeConfig from "./mode_config_type";
export { ModeConfig };
import ModeRules from "./mode_rules_type";
export { ModeRules };
import MonitoringSettings from "./monitoring_settings_type";
export { MonitoringSettings };
import MonitoringSettingsClub from "./monitoring_settings_club_type";
export { MonitoringSettingsClub };
import MonitoringSettingsMap from "./monitoring_settings_map_type";
export { MonitoringSettingsMap };
import MyTournamentV1 from "./my_tournament_v_1_type";
export { MyTournamentV1 };
import NodeKindHandle from "./node_kind_handle_type";
export { NodeKindHandle };
import PlayLoopEnd from "./play_loop_end_type";
export { PlayLoopEnd };
import PlayLoopStart from "./play_loop_start_type";
export { PlayLoopStart };
import Player from "./player_type";
export { Player };
import PlayerChat from "./player_chat_type";
export { PlayerChat };
import PlayerConnect from "./player_connect_type";
export { PlayerConnect };
import PlayerDisconnect from "./player_disconnect_type";
export { PlayerDisconnect };
import Podium from "./podium_type";
export { Podium };
import RawServerV1 from "./raw_server_v_1_type";
export { RawServerV1 };
import RegisteredPlayer from "./registered_player_type";
export { RegisteredPlayer };
import RegisteredTeam from "./registered_team_type";
export { RegisteredTeam };
import RegistrationPlayerSettings from "./registration_player_settings_type";
export { RegistrationPlayerSettings };
import RegistrationSettings from "./registration_settings_type";
export { RegistrationSettings };
import RegistrationTeamSettings from "./registration_team_settings_type";
export { RegistrationTeamSettings };
import Respawn from "./respawn_type";
export { Respawn };
import RespawnBehaviour from "./respawn_behaviour_type";
export { RespawnBehaviour };
import RoundStandings from "./round_standings_type";
export { RoundStandings };
import RoundTime from "./round_time_type";
export { RoundTime };
import Rounds from "./rounds_type";
export { Rounds };
import ScheduleV1 from "./schedule_v_1_type";
export { ScheduleV1 };
import Scores from "./scores_type";
export { Scores };
import ServerConfig from "./server_config_type";
export { ServerConfig };
import ServerOptions from "./server_options_type";
export { ServerOptions };
import ServerState from "./server_state_type";
export { ServerState };
import StartLine from "./start_line_type";
export { StartLine };
import StartMap from "./start_map_type";
export { StartMap };
import StartMatch from "./start_match_type";
export { StartMatch };
import StartRound from "./start_round_type";
export { StartRound };
import StartServer from "./start_server_type";
export { StartServer };
import StartTurn from "./start_turn_type";
export { StartTurn };
import TabCompetitionConnection from "./tab_competition_connection_type";
export { TabCompetitionConnection };
import Team from "./team_type";
export { Team };
import TmCompRecord from "./tm_comp_record_type";
export { TmCompRecord };
import TmMapRecord from "./tm_map_record_type";
export { TmMapRecord };
import TmMatchEvent from "./tm_match_event_type";
export { TmMatchEvent };
import TmMatchPlayer from "./tm_match_player_type";
export { TmMatchPlayer };
import TmMatchState from "./tm_match_state_type";
export { TmMatchState };
import TmMatchV1 from "./tm_match_v_1_type";
export { TmMatchV1 };
import TmMonitoring from "./tm_monitoring_type";
export { TmMonitoring };
import TmRecord from "./tm_record_type";
export { TmRecord };
import TmServerConfig from "./tm_server_config_type";
export { TmServerConfig };
import TmServerMethodCall from "./tm_server_method_call_type";
export { TmServerMethodCall };
import TmServerMethodResponse from "./tm_server_method_response_type";
export { TmServerMethodResponse };
import TmWorker from "./tm_worker_type";
export { TmWorker };
import TmWorkerJobs from "./tm_worker_jobs_type";
export { TmWorkerJobs };
import TournamentStatus from "./tournament_status_type";
export { TournamentStatus };
import TournamentStatusScheduleV1 from "./tournament_status_schedule_v_1_type";
export { TournamentStatusScheduleV1 };
import TournamentV1 from "./tournament_v_1_type";
export { TournamentV1 };
import UnloadingMapEnd from "./unloading_map_end_type";
export { UnloadingMapEnd };
import UnloadingMapStart from "./unloading_map_start_type";
export { UnloadingMapStart };
import User from "./user_type";
export { User };
import UserIdentity from "./user_identity_type";
export { UserIdentity };
import WarmupDuration from "./warmup_duration_type";
export { WarmupDuration };
import WarmupRound from "./warmup_round_type";
export { WarmupRound };
import WarmupTimeout from "./warmup_timeout_type";
export { WarmupTimeout };
import WayPoint from "./way_point_type";
export { WayPoint };

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema(
  __table({
    name: 'env',
    indexes: [
      { name: 'key', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'env_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, EnvRow),
  __table({
    name: 'generator',
    indexes: [
    ],
    constraints: [
    ],
  }, GeneratorRow),
  __table({
    name: 'match_ghost',
    indexes: [
    ],
    constraints: [
    ],
  }, MatchGhostRow),
  __table({
    name: 'match_template',
    indexes: [
      { name: 'creator', algorithm: 'btree', columns: [
        'creator',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'match_template_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MatchTemplateRow),
  __table({
    name: 'tab_competition',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'tab_competition_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TabCompetitionRow),
  __table({
    name: 'tab_competition_connection',
    indexes: [
      { name: 'competition_id', algorithm: 'btree', columns: [
        'competitionId',
      ] },
      { name: 'connection_exists', algorithm: 'btree', columns: [
        'connectionFromVariant',
        'connectionFrom',
        'connectionToVariant',
        'connectionTo',
      ] },
    ],
    constraints: [
    ],
  }, TabCompetitionConnectionRow),
  __table({
    name: 'tab_raw_server_offline',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
      { name: 'owner_id', algorithm: 'btree', columns: [
        'ownerId',
      ] },
      { name: 'tm_login', algorithm: 'btree', columns: [
        'tmLogin',
      ] },
    ],
    constraints: [
      { name: 'tab_raw_server_offline_identity_key', constraint: 'unique', columns: ['identity'] },
      { name: 'tab_raw_server_offline_tm_login_key', constraint: 'unique', columns: ['tmLogin'] },
    ],
  }, TabRawServerOfflineRow),
  __table({
    name: 'tab_raw_server_online',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
      { name: 'owner_id', algorithm: 'btree', columns: [
        'ownerId',
      ] },
      { name: 'tm_login', algorithm: 'btree', columns: [
        'tmLogin',
      ] },
    ],
    constraints: [
      { name: 'tab_raw_server_online_identity_key', constraint: 'unique', columns: ['identity'] },
      { name: 'tab_raw_server_online_tm_login_key', constraint: 'unique', columns: ['tmLogin'] },
    ],
  }, TabRawServerOnlineRow),
  __table({
    name: 'tab_registered_player',
    indexes: [
      { name: 'competition_id', algorithm: 'btree', columns: [
        'competitionId',
      ] },
    ],
    constraints: [
    ],
  }, TabRegisteredPlayerRow),
  __table({
    name: 'tab_registered_team',
    indexes: [
      { name: 'competition_id', algorithm: 'btree', columns: [
        'competitionId',
      ] },
    ],
    constraints: [
    ],
  }, TabRegisteredTeamRow),
  __table({
    name: 'tab_schedule',
    indexes: [
      { name: 'scheduled_id', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'tab_schedule_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, TabScheduleRow),
  __table({
    name: 'tab_tm_match',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'tab_tm_match_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TabTmMatchRow),
  __table({
    name: 'tab_tm_match_event',
    indexes: [
      { name: 'event', algorithm: 'btree', columns: [
        'event',
      ] },
      { name: 'match_id', algorithm: 'btree', columns: [
        'matchId',
      ] },
      { name: 'match_round_wu', algorithm: 'btree', columns: [
        'matchId',
        'round',
        'isWarmup',
      ] },
    ],
    constraints: [
    ],
  }, TabTmMatchEventRow),
  __table({
    name: 'tab_tm_match_players',
    indexes: [
      { name: 'account_id', algorithm: 'btree', columns: [
        'accountId',
      ] },
      { name: 'match_id', algorithm: 'btree', columns: [
        'matchId',
      ] },
    ],
    constraints: [
      { name: 'tab_tm_match_players_account_id_key', constraint: 'unique', columns: ['accountId'] },
    ],
  }, TabTmMatchPlayersRow),
  __table({
    name: 'tab_tm_match_spectators',
    indexes: [
      { name: 'account_id', algorithm: 'btree', columns: [
        'accountId',
      ] },
      { name: 'match_id', algorithm: 'btree', columns: [
        'matchId',
      ] },
    ],
    constraints: [
      { name: 'tab_tm_match_spectators_account_id_key', constraint: 'unique', columns: ['accountId'] },
    ],
  }, TabTmMatchSpectatorsRow),
  __table({
    name: 'tab_tm_match_state',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'tab_tm_match_state_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TabTmMatchStateRow),
  __table({
    name: 'tab_tournament',
    indexes: [
      { name: 'creator', algorithm: 'btree', columns: [
        'creator',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'name', algorithm: 'btree', columns: [
        'name',
      ] },
    ],
    constraints: [
      { name: 'tab_tournament_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'tab_tournament_name_key', constraint: 'unique', columns: ['name'] },
    ],
  }, TabTournamentRow),
  __table({
    name: 'tab_tournament_status_schedule',
    indexes: [
      { name: 'scheduled_id', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
      { name: 'tournament_id', algorithm: 'btree', columns: [
        'tournamentId',
      ] },
    ],
    constraints: [
      { name: 'tab_tournament_status_schedule_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
      { name: 'tab_tournament_status_schedule_tournament_id_key', constraint: 'unique', columns: ['tournamentId'] },
    ],
  }, TabTournamentStatusScheduleRow),
  __table({
    name: 'tab_user',
    indexes: [
      { name: 'account_id', algorithm: 'btree', columns: [
        'accountId',
      ] },
    ],
    constraints: [
      { name: 'tab_user_account_id_key', constraint: 'unique', columns: ['accountId'] },
    ],
  }, TabUserRow),
  __table({
    name: 'tm_map_record',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'record_id', algorithm: 'btree', columns: [
        'mapUid',
        'playerUid',
      ] },
    ],
    constraints: [
      { name: 'tm_map_record_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TmMapRecordRow),
  __table({
    name: 'tm_match_record',
    indexes: [
      { name: 'record_id', algorithm: 'btree', columns: [
        'matchId',
        'mapUid',
        'playerUid',
      ] },
    ],
    constraints: [
    ],
  }, TmMatchRecordRow),
  __table({
    name: 'tm_monitoring',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'tm_monitoring_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TmMonitoringRow),
  __table({
    name: 'tm_server_config',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'tm_server_config_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TmServerConfigRow),
  __table({
    name: 'tm_server_method_call',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'tm_server_method_call_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TmServerMethodCallRow),
  __table({
    name: 'tm_server_method_response',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'tm_server_method_response_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TmServerMethodResponseRow),
  __table({
    name: 'tm_worker',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
      { name: 'tm_login', algorithm: 'btree', columns: [
        'tmLogin',
      ] },
    ],
    constraints: [
      { name: 'tm_worker_identity_key', constraint: 'unique', columns: ['identity'] },
      { name: 'tm_worker_tm_login_key', constraint: 'unique', columns: ['tmLogin'] },
    ],
  }, TmWorkerRow),
  __table({
    name: 'tm_worker_jobs',
    indexes: [
      { name: 'worker_id', algorithm: 'btree', columns: [
        'tmLogin',
      ] },
    ],
    constraints: [
    ],
  }, TmWorkerJobsRow),
  __table({
    name: 'user_identity',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'user_identity_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, UserIdentityRow),
  __table({
    name: 'competition',
    indexes: [
    ],
    constraints: [
    ],
  }, CompetitionRow),
  __table({
    name: 'competition_connection',
    indexes: [
    ],
    constraints: [
    ],
  }, CompetitionConnectionRow),
  __table({
    name: 'competition_record',
    indexes: [
    ],
    constraints: [
    ],
  }, CompetitionRecordRow),
  __table({
    name: 'map_record',
    indexes: [
    ],
    constraints: [
    ],
  }, MapRecordRow),
  __table({
    name: 'match_leaderbaord',
    indexes: [
    ],
    constraints: [
    ],
  }, MatchLeaderbaordRow),
  __table({
    name: 'match_players',
    indexes: [
    ],
    constraints: [
    ],
  }, MatchPlayersRow),
  __table({
    name: 'match_record',
    indexes: [
    ],
    constraints: [
    ],
  }, MatchRecordRow),
  __table({
    name: 'match_round',
    indexes: [
    ],
    constraints: [
    ],
  }, MatchRoundRow),
  __table({
    name: 'my_jobs',
    indexes: [
    ],
    constraints: [
    ],
  }, MyJobsRow),
  __table({
    name: 'my_match_template',
    indexes: [
    ],
    constraints: [
    ],
  }, MyMatchTemplateRow),
  __table({
    name: 'my_tournament',
    indexes: [
    ],
    constraints: [
    ],
  }, MyTournamentRow),
  __table({
    name: 'raw_server',
    indexes: [
    ],
    constraints: [
    ],
  }, RawServerRow),
  __table({
    name: 'raw_server_current_players',
    indexes: [
    ],
    constraints: [
    ],
  }, RawServerCurrentPlayersRow),
  __table({
    name: 'raw_server_expected_players',
    indexes: [
    ],
    constraints: [
    ],
  }, RawServerExpectedPlayersRow),
  __table({
    name: 'registered_player',
    indexes: [
    ],
    constraints: [
    ],
  }, RegisteredPlayerRow),
  __table({
    name: 'schedule',
    indexes: [
    ],
    constraints: [
    ],
  }, ScheduleRow),
  __table({
    name: 'this_raw_server',
    indexes: [
    ],
    constraints: [
    ],
  }, ThisRawServerRow),
  __table({
    name: 'tm_match',
    indexes: [
    ],
    constraints: [
    ],
  }, TmMatchRow),
  __table({
    name: 'tournament',
    indexes: [
    ],
    constraints: [
    ],
  }, TournamentRow),
  __table({
    name: 'user',
    indexes: [
    ],
    constraints: [
    ],
  }, UserRow),
);

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("competition_edit_name", CompetitionEditNameReducer),
  __reducerSchema("competition_registration_settings", CompetitionRegistrationSettingsReducer),
  __reducerSchema("create_competition", CreateCompetitionReducer),
  __reducerSchema("create_connection", CreateConnectionReducer),
  __reducerSchema("create_env_var", CreateEnvVarReducer),
  __reducerSchema("create_event_template", CreateEventTemplateReducer),
  __reducerSchema("create_match", CreateMatchReducer),
  __reducerSchema("create_match_template", CreateMatchTemplateReducer),
  __reducerSchema("create_monitor", CreateMonitorReducer),
  __reducerSchema("create_schedule", CreateScheduleReducer),
  __reducerSchema("create_server_config", CreateServerConfigReducer),
  __reducerSchema("create_team", CreateTeamReducer),
  __reducerSchema("create_tournament", CreateTournamentReducer),
  __reducerSchema("internal_graph_resolution_node_finished", InternalGraphResolutionNodeFinishedReducer),
  __reducerSchema("match_assign_server", MatchAssignServerReducer),
  __reducerSchema("match_configured", MatchConfiguredReducer),
  __reducerSchema("on_schedule_triggered", OnScheduleTriggeredReducer),
  __reducerSchema("on_tournament_status_schedule_triggered", OnTournamentStatusScheduleTriggeredReducer),
  __reducerSchema("post_event", PostEventReducer),
  __reducerSchema("post_record", PostRecordReducer),
  __reducerSchema("register_player", RegisterPlayerReducer),
  __reducerSchema("server_method_call", ServerMethodCallReducer),
  __reducerSchema("server_method_response", ServerMethodResponseReducer),
  __reducerSchema("tournament_edit_dates", TournamentEditDatesReducer),
  __reducerSchema("tournament_edit_description", TournamentEditDescriptionReducer),
  __reducerSchema("tournament_edit_name", TournamentEditNameReducer),
  __reducerSchema("tournament_update_status", TournamentUpdateStatusReducer),
  __reducerSchema("try_start_match", TryStartMatchReducer),
  __reducerSchema("unregister_player", UnregisterPlayerReducer),
  __reducerSchema("update_match_config", UpdateMatchConfigReducer),
  __reducerSchema("update_pre_match_config", UpdatePreMatchConfigReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
  __procedureSchema("login_as_server", LoginAsServerProcedure.params, LoginAsServerProcedure.returnType),
  __procedureSchema("login_as_worker", LoginAsWorkerProcedure.params, LoginAsWorkerProcedure.returnType),
  __procedureSchema("post_round_replay", PostRoundReplayProcedure.params, PostRoundReplayProcedure.returnType),
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "1.11.1" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. */
export const tables = __convertToAccessorMap(tablesSchema.schemaType.tables);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

