// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import MatchState from "./match_state_type";
import Event from "./event_type";


export default __t.row({
  tournamentId: __t.u32().name("tournament_id"),
  matchId: __t.u32().name("match_id"),
  get state() {
    return MatchState;
  },
  get event() {
    return Event;
  },
});
