// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import ChatSendServerMessageToUserArgs from "./chat_send_server_message_to_user_args_type";
import ChatSendToUserArgs from "./chat_send_to_user_args_type";
import KickArgs from "./kick_args_type";
import BanArgs from "./ban_args_type";


// The tagged union or sum type for the algebraic type `MethodCall`.
const MethodCall = __t.enum("MethodCall", {ListMethods: __t.unit(),
  MethodSignature: __t.string(),
  MethodHelp: __t.string(),
  ChatSendServerMessage: __t.string(),
  get ChatSendServerMessageToUser() {
    return ChatSendServerMessageToUserArgs;
  },
  ChatSend: __t.string(),
  get ChatSendToUser() {
    return ChatSendToUserArgs;
  },
  get Kick() {
    return KickArgs;
  },
  get Ban() {
    return BanArgs;
  },
  UnBan: __t.string(),
  Ignore: __t.string(),
  UnIgnore: __t.string(),
  SetPlayerPassword: __t.string(),
  SetSpectatorPassword: __t.string(),
  SendToServerAfterMatchEnd: __t.string(),
  GetMethodsList: __t.unit(),
  PauseSetActive: __t.bool(),
});

export default MethodCall;


