// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import TournamentStatus from "./tournament_status_type";


export default __t.object("MyTournamentV1", {
  id: __t.u32(),
  creator: __t.string(),
  creatorName: __t.string(),
  name: __t.string(),
  startingAt: __t.timestamp(),
  endingAt: __t.timestamp(),
  description: __t.string(),
  get status() {
    return TournamentStatus;
  },
});


