// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

// The tagged union or sum type for the algebraic type `NodeKindRef`.
const NodeKindRef = __t.enum("NodeKindRef", {MatchV1: __t.u32(),
  CompetitionV1: __t.u32(),
  MonitoringV1: __t.u32(),
  ServerV1: __t.u32(),
  SchedulingV1: __t.u32(),
});

export default NodeKindRef;


