// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("PlayerInfo", {
  accountId: __t.string(),
  nickName: __t.string(),
  playerId: __t.i32(),
  teamId: __t.i32(),
  spectatorStatus: __t.i32(),
  ladderRanking: __t.i32(),
  flags: __t.i32(),
});


