// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import RegistrationPlayerRules from "./registration_player_rules_type";
import RegistrationTeamRules from "./registration_team_rules_type";


// The tagged union or sum type for the algebraic type `RegistrationRules`.
const RegistrationRules = __t.enum("RegistrationRules", {get Players() {
    return RegistrationPlayerRules;
  },
  get Team() {
    return RegistrationTeamRules;
  },
  Inherit: __t.unit(),
  Open: __t.unit(),
});

export default RegistrationRules;


