// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import RegistrationPlayerSettings from "./registration_player_settings_type";
import RegistrationTeamSettings from "./registration_team_settings_type";


// The tagged union or sum type for the algebraic type `RegistrationSettings`.
const RegistrationSettings = __t.enum("RegistrationSettings", {get Players() {
    return RegistrationPlayerSettings;
  },
  get Team() {
    return RegistrationTeamSettings;
  },
  None: __t.unit(),
});

export default RegistrationSettings;


