// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

// The tagged union or sum type for the algebraic type `RespawnBavaviour`.
const RespawnBavaviour = __t.enum("RespawnBavaviour", {Default: __t.unit(),
  TimeAttack: __t.unit(),
  Ignore: __t.unit(),
  GiveUpAtStart: __t.unit(),
  GiveUpAlways: __t.unit(),
  GiveUpNever: __t.unit(),
});

export default RespawnBavaviour;


