// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import FinishTimeout from "./finish_timeout_type";
import MapsPerMatch from "./maps_per_match_type";
import PointsLimit from "./points_limit_type";
import RoundsPerMap from "./rounds_per_map_type";


export default __t.object("Rounds", {
  get finishTimeout() {
    return FinishTimeout;
  },
  get mapsPerMatch() {
    return MapsPerMatch;
  },
  get pointsLimit() {
    return PointsLimit;
  },
  useCustomPointsRepartition: __t.bool(),
  pointsRepartition: __t.array(__t.u32()),
  get roundsPerMap() {
    return RoundsPerMap;
  },
  useTieBreaker: __t.bool(),
});


