// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import ServerConfig from "./server_config_type";
import MatchState from "./match_state_type";
import MatchStatus from "./match_status_type";
import MatchEntityRules from "./match_entity_rules_type";


export default __t.row({
  id: __t.u32().primaryKey(),
  tournamentId: __t.u32().name("tournament_id"),
  competitionId: __t.u32().name("competition_id"),
  serverId: __t.option(__t.string()).name("server_id"),
  get preMatchConfig() {
    return __t.option(ServerConfig).name("pre_match_config");
  },
  get matchConfig() {
    return __t.option(ServerConfig).name("match_config");
  },
  get postMatchConfig() {
    return __t.option(ServerConfig).name("post_match_config");
  },
  get status() {
    return MatchStatus;
  },
  get state() {
    return MatchState;
  },
  get permittedEntities() {
    return MatchEntityRules.name("permitted_entities");
  },
});
