// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import ConnectionSettings from "./connection_settings_type";


export default __t.row({
  id: __t.u32().primaryKey(),
  competitionId: __t.u32().name("competition_id"),
  tournamentId: __t.u32().name("tournament_id"),
  connectionFrom: __t.u32().name("connection_from"),
  connectionTo: __t.u32().name("connection_to"),
  connectionFromVariant: __t.u8().name("connection_from_variant"),
  connectionToVariant: __t.u8().name("connection_to_variant"),
  get connectionSettings() {
    return ConnectionSettings.name("connection_settings");
  },
  resolved: __t.bool(),
});
