// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import Vec2 from "./vec_2_type";


export default __t.object("TabCompetitionNodePosition", {
  id: __t.u32(),
  competitionId: __t.u32(),
  nodeId: __t.u32(),
  nodeVariant: __t.u8(),
  get position() {
    return Vec2;
  },
});


