// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import Event from "./event_type";


export default __t.object("TmMatchEvent", {
  matchId: __t.u32(),
  restarted: __t.u16(),
  round: __t.u16(),
  warmup: __t.u16(),
  isWarmup: __t.bool(),
  paused: __t.bool(),
  get event() {
    return Event;
  },
});


