// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import MatchStatus from "./match_status_type";


export default __t.object("TmMatchV1", {
  name: __t.string(),
  id: __t.u32(),
  tournamentId: __t.u32(),
  competitionId: __t.u32(),
  preMatchConfig: __t.u32(),
  matchConfig: __t.u32(),
  postMatchConfig: __t.u32(),
  get status() {
    return MatchStatus;
  },
});


