// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  MatchStatus,
} from "./types";


export default __t.row({
  name: __t.string(),
  id: __t.u32(),
  projectId: __t.u32().name("project_id"),
  competitionId: __t.u32().name("competition_id"),
  preMatchConfig: __t.u32().name("pre_match_config"),
  matchConfig: __t.u32().name("match_config"),
  postMatchConfig: __t.u32().name("post_match_config"),
  get status() {
    return MatchStatus;
  },
  autoProvisionServer: __t.bool().name("auto_provision_server"),
});
