// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import Scheduling from "./scheduling_type";
import ServerConfig from "./server_config_type";
import MatchState from "./match_state_type";
import MatchStatus from "./match_status_type";
import MatchEntityRules from "./match_entity_rules_type";
import MatchLeaderboardRules from "./match_leaderboard_rules_type";


export default __t.object("TmMatch", {
  id: __t.u32(),
  tournamentId: __t.u32(),
  competitionId: __t.u32(),
  get scheduling() {
    return Scheduling;
  },
  serverId: __t.option(__t.string()),
  get preMatchConfig() {
    return __t.option(ServerConfig);
  },
  get matchConfig() {
    return __t.option(ServerConfig);
  },
  get postMatchConfig() {
    return __t.option(ServerConfig);
  },
  get status() {
    return MatchStatus;
  },
  get state() {
    return MatchState;
  },
  get permittedEntities() {
    return MatchEntityRules;
  },
  get leaderboard() {
    return MatchLeaderboardRules;
  },
});


