// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import MonitoringSettings from "./monitoring_settings_type";


export default __t.row({
  id: __t.u32().primaryKey(),
  tournament: __t.u32(),
  competition: __t.u32(),
  get settings() {
    return MonitoringSettings;
  },
  name: __t.option(__t.string()),
  active: __t.bool(),
});
