// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import TournamentStatus from "./tournament_status_type";


export default __t.row({
  id: __t.u32(),
  creatorAccountId: __t.uuid().name("creator_account_id"),
  name: __t.string(),
  startingAt: __t.timestamp().name("starting_at"),
  endingAt: __t.timestamp().name("ending_at"),
  description: __t.string(),
  get status() {
    return TournamentStatus;
  },
});
