// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import TournamentStatus from "./tournament_status_type";


export default __t.object("TournamentStatusScheduleV1", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  tournamentId: __t.u32(),
  get newStatus() {
    return TournamentStatus;
  },
});


