// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const BanArgs = __t.object("BanArgs", {
  ubiId: __t.string(),
  message: __t.option(__t.string()),
});
export type BanArgs = __Infer<typeof BanArgs>;

export const ChatSendServerMessageToUserArgs = __t.object("ChatSendServerMessageToUserArgs", {
  login: __t.string(),
  message: __t.string(),
});
export type ChatSendServerMessageToUserArgs = __Infer<typeof ChatSendServerMessageToUserArgs>;

export const ChatSendToUserArgs = __t.object("ChatSendToUserArgs", {
  login: __t.string(),
  message: __t.string(),
});
export type ChatSendToUserArgs = __Infer<typeof ChatSendToUserArgs>;

export const Common = __t.object("Common", {
  chatTime: __t.u32(),
  get respawnBehaviour() {
    return RespawnBehaviour;
  },
  delayBeforeNextMap: __t.u32(),
  synchronizePlayersAtMapStart: __t.bool(),
  synchronizePlayersAtRoundStart: __t.bool(),
  trustClientSimulation: __t.bool(),
  useCrudeExtrapolation: __t.bool(),
  get warmupDuration() {
    return WarmupDuration;
  },
  get warmupTimeout() {
    return WarmupTimeout;
  },
  warmupNumber: __t.u32(),
  decoImageUrlCheckpoint: __t.string(),
  decoImageUrlDecalSponsor4X1: __t.string(),
  decoImageUrlScreen16X1: __t.string(),
  decoImageUrlScreen16X9: __t.string(),
  decoImageUrlScreen8X1: __t.string(),
  decoImageUrlWhoAmIUrl: __t.string(),
  get forceLapsNumber() {
    return LapsNumber;
  },
});
export type Common = __Infer<typeof Common>;

export const CompetitionConnection = __t.object("CompetitionConnection", {
  projectId: __t.u32(),
  competitionId: __t.u32(),
  get connectionFrom() {
    return NodeKindHandle;
  },
  get connectionTo() {
    return NodeKindHandle;
  },
  get connectionSettings() {
    return ConnectionSettings;
  },
});
export type CompetitionConnection = __Infer<typeof CompetitionConnection>;

export const CompetitionConnectionData = __t.object("CompetitionConnectionData", {
  competitionId: __t.u32(),
  connectionId: __t.u32(),
  countTop: __t.option(__t.u8()),
  countBottom: __t.option(__t.u8()),
  customList: __t.byteArray(),
});
export type CompetitionConnectionData = __Infer<typeof CompetitionConnectionData>;

// The tagged union or sum type for the algebraic type `CompetitionConnectionDataOption`.
export const CompetitionConnectionDataOption = __t.enum("CompetitionConnectionDataOption", {
  All: __t.unit(),
  First: __t.u8(),
  Last: __t.u8(),
  Custom: __t.byteArray(),
});
export type CompetitionConnectionDataOption = __Infer<typeof CompetitionConnectionDataOption>;

export const CompetitionNodePosition = __t.object("CompetitionNodePosition", {
  competitionId: __t.u32(),
  get node() {
    return NodeKindHandle;
  },
  get position() {
    return Vec2;
  },
});
export type CompetitionNodePosition = __Infer<typeof CompetitionNodePosition>;

// The tagged union or sum type for the algebraic type `CompetitionStatus`.
export const CompetitionStatus = __t.enum("CompetitionStatus", {
  Planning: __t.unit(),
  Registration: __t.unit(),
  Ongoing: __t.unit(),
  Completed: __t.unit(),
});
export type CompetitionStatus = __Infer<typeof CompetitionStatus>;

export const CompetitionV1 = __t.object("CompetitionV1", {
  id: __t.u32(),
  projectId: __t.u32(),
  parentId: __t.u32(),
  name: __t.string(),
  get status() {
    return CompetitionStatus;
  },
  startingAt: __t.option(__t.timestamp()),
  endingAt: __t.option(__t.timestamp()),
  get registrationSettings() {
    return RegistrationSettings;
  },
});
export type CompetitionV1 = __Infer<typeof CompetitionV1>;

// The tagged union or sum type for the algebraic type `ConnectionSettings`.
export const ConnectionSettings = __t.enum("ConnectionSettings", {
  Waiting: __t.unit(),
  Data: __t.unit(),
});
export type ConnectionSettings = __Infer<typeof ConnectionSettings>;

export const Custom = __t.object("Custom", {
  name: __t.string(),
  body: __t.string(),
});
export type Custom = __Infer<typeof Custom>;

export const EndMapEnd = __t.object("EndMapEnd", {
  count: __t.u32(),
  valid: __t.u32(),
  isValid: __t.bool(),
  time: __t.u32(),
  get map() {
    return Map;
  },
});
export type EndMapEnd = __Infer<typeof EndMapEnd>;

export const EndMapStart = __t.object("EndMapStart", {
  count: __t.u32(),
  valid: __t.u32(),
  get map() {
    return Map;
  },
});
export type EndMapStart = __Infer<typeof EndMapStart>;

export const EndMatch = __t.object("EndMatch", {
  count: __t.u32(),
  time: __t.u32(),
});
export type EndMatch = __Infer<typeof EndMatch>;

export const EndRoundEnd = __t.object("EndRoundEnd", {
  count: __t.u32(),
  valid: __t.u32(),
  time: __t.u32(),
  isValid: __t.bool(),
});
export type EndRoundEnd = __Infer<typeof EndRoundEnd>;

export const EndRoundStart = __t.object("EndRoundStart", {
  count: __t.u32(),
  valid: __t.u32(),
  time: __t.u32(),
});
export type EndRoundStart = __Infer<typeof EndRoundStart>;

export const EndServer = __t.object("EndServer", {
  time: __t.u32(),
});
export type EndServer = __Infer<typeof EndServer>;

export const EndTurnEnd = __t.object("EndTurnEnd", {
  count: __t.u32(),
  valid: __t.u32(),
  time: __t.u32(),
  isValid: __t.bool(),
});
export type EndTurnEnd = __Infer<typeof EndTurnEnd>;

export const EndTurnStart = __t.object("EndTurnStart", {
  count: __t.u32(),
  valid: __t.u32(),
  time: __t.u32(),
});
export type EndTurnStart = __Infer<typeof EndTurnStart>;

export const Env = __t.object("Env", {
  key: __t.string(),
  value: __t.string(),
});
export type Env = __Infer<typeof Env>;

// The tagged union or sum type for the algebraic type `Event`.
export const Event = __t.enum("Event", {
  get WayPoint() {
    return WayPoint;
  },
  get Respawn() {
    return Respawn;
  },
  get StartLine() {
    return StartLine;
  },
  get Scores() {
    return Scores;
  },
  get GiveUp() {
    return GiveUp;
  },
  get LoadingMapStart() {
    return LoadingMapStart;
  },
  get LoadingMapEnd() {
    return LoadingMapEnd;
  },
  get StartMapStart() {
    return StartMap;
  },
  get StartMapEnd() {
    return StartMap;
  },
  get EndMapStart() {
    return EndMapStart;
  },
  get EndMapEnd() {
    return EndMapEnd;
  },
  get UnloadingMapStart() {
    return UnloadingMapStart;
  },
  get UnloadingMapEnd() {
    return UnloadingMapEnd;
  },
  get PlayerConenct() {
    return PlayerConnect;
  },
  get PlayerDisconnect() {
    return PlayerDisconnect;
  },
  get PlayerChat() {
    return PlayerChat;
  },
  get PlayerInfoChanged() {
    return PlayerInfo;
  },
  get StartTurnStart() {
    return StartTurn;
  },
  get StartTurnEnd() {
    return StartTurn;
  },
  get EndTurnStart() {
    return EndTurnStart;
  },
  get EndTurnEnd() {
    return EndTurnEnd;
  },
  get PlayLoopStart() {
    return PlayLoopStart;
  },
  get PlayLoopEnd() {
    return PlayLoopEnd;
  },
  get StartRoundStart() {
    return StartRound;
  },
  get StartRoundEnd() {
    return StartRound;
  },
  get EndRoundStart() {
    return EndRoundStart;
  },
  get EndRoundEnd() {
    return EndRoundEnd;
  },
  get PodiumStart() {
    return Podium;
  },
  get PodiumEnd() {
    return Podium;
  },
  get StartMatchStart() {
    return StartMatch;
  },
  get StartMatchEnd() {
    return StartMatch;
  },
  get EndMatchStart() {
    return EndMatch;
  },
  get EndMatchEnd() {
    return EndMatch;
  },
  get StartServerStart() {
    return StartServer;
  },
  get StartServerEnd() {
    return StartServer;
  },
  get EndServerStart() {
    return EndServer;
  },
  get EndServerEnd() {
    return EndServer;
  },
  WarmupStart: __t.unit(),
  WarmupEnd: __t.unit(),
  get WarmupStartRound() {
    return WarmupRound;
  },
  get WarmupEndRound() {
    return WarmupRound;
  },
  get Pause() {
    return Pause;
  },
  get Custom() {
    return Custom;
  },
});
export type Event = __Infer<typeof Event>;

// The tagged union or sum type for the algebraic type `FinishTimeout`.
export const FinishTimeout = __t.enum("FinishTimeout", {
  BasedOnMedal: __t.unit(),
  Seconds: __t.u32(),
});
export type FinishTimeout = __Infer<typeof FinishTimeout>;

export const GiveUp = __t.object("GiveUp", {
  accountId: __t.string(),
  time: __t.u32(),
});
export type GiveUp = __Infer<typeof GiveUp>;

export const KickArgs = __t.object("KickArgs", {
  ubiId: __t.string(),
  message: __t.option(__t.string()),
});
export type KickArgs = __Infer<typeof KickArgs>;

// The tagged union or sum type for the algebraic type `LapsNumber`.
export const LapsNumber = __t.enum("LapsNumber", {
  Validation: __t.unit(),
  Independent: __t.unit(),
  Laps: __t.u32(),
});
export type LapsNumber = __Infer<typeof LapsNumber>;

// The tagged union or sum type for the algebraic type `LastChanceDnfMode`.
export const LastChanceDnfMode = __t.enum("LastChanceDnfMode", {
  AllPlayers: __t.unit(),
  OnlyLeastCheckpoints: __t.unit(),
});
export type LastChanceDnfMode = __Infer<typeof LastChanceDnfMode>;

export const LoadingMapEnd = __t.object("LoadingMapEnd", {
  restarted: __t.bool(),
  time: __t.u32(),
  get map() {
    return Map;
  },
});
export type LoadingMapEnd = __Infer<typeof LoadingMapEnd>;

export const LoadingMapStart = __t.object("LoadingMapStart", {
  restarted: __t.bool(),
  time: __t.u32(),
});
export type LoadingMapStart = __Infer<typeof LoadingMapStart>;

export const Map = __t.object("Map", {
  uid: __t.string(),
  name: __t.string(),
  filename: __t.string(),
  authorAccountId: __t.string(),
  authorNickname: __t.string(),
  environment: __t.string(),
  mood: __t.string(),
  bronzeTime: __t.u32(),
  silverTime: __t.u32(),
  goldTime: __t.u32(),
  authorTime: __t.u32(),
  copperprice: __t.u32(),
  lapRace: __t.bool(),
  numberLaps: __t.u32(),
  mapType: __t.string(),
  mapStyle: __t.string(),
});
export type Map = __Infer<typeof Map>;

export const MapPoolConfig = __t.object("MapPoolConfig", {
  start: __t.u32(),
  mapUids: __t.array(__t.string()),
});
export type MapPoolConfig = __Infer<typeof MapPoolConfig>;

// The tagged union or sum type for the algebraic type `MapsPerMatch`.
export const MapsPerMatch = __t.enum("MapsPerMatch", {
  One: __t.unit(),
  Maps: __t.u32(),
});
export type MapsPerMatch = __Infer<typeof MapsPerMatch>;

export const MatchGhost = __t.object("MatchGhost", {
  projectId: __t.u32(),
  matchId: __t.u32(),
  playerId: __t.uuid(),
  uid: __t.uuid(),
});
export type MatchGhost = __Infer<typeof MatchGhost>;

// The tagged union or sum type for the algebraic type `MatchStatus`.
export const MatchStatus = __t.enum("MatchStatus", {
  Configuring: __t.unit(),
  Upcoming: __t.unit(),
  Live: __t.unit(),
  Ended: __t.unit(),
});
export type MatchStatus = __Infer<typeof MatchStatus>;

export const MatchTemplate = __t.object("MatchTemplate", {
  name: __t.string(),
  creator: __t.uuid(),
  id: __t.u32(),
  configId: __t.u32(),
});
export type MatchTemplate = __Infer<typeof MatchTemplate>;

// The tagged union or sum type for the algebraic type `MethodCall`.
export const MethodCall = __t.enum("MethodCall", {
  ListMethods: __t.unit(),
  MethodSignature: __t.string(),
  MethodHelp: __t.string(),
  ChatSendServerMessage: __t.string(),
  get ChatSendServerMessageToUser() {
    return ChatSendServerMessageToUserArgs;
  },
  ChatSend: __t.string(),
  get ChatSendToUser() {
    return ChatSendToUserArgs;
  },
  get Kick() {
    return KickArgs;
  },
  get Ban() {
    return BanArgs;
  },
  UnBan: __t.string(),
  Ignore: __t.string(),
  UnIgnore: __t.string(),
  SetPlayerPassword: __t.string(),
  SetSpectatorPassword: __t.string(),
  SendToServerAfterMatchEnd: __t.string(),
  GetMethodsList: __t.unit(),
  PauseSetActive: __t.bool(),
});
export type MethodCall = __Infer<typeof MethodCall>;

export const MethodError = __t.object("MethodError", {
  code: __t.i32(),
  message: __t.string(),
});
export type MethodError = __Infer<typeof MethodError>;

// The tagged union or sum type for the algebraic type `MethodResponse`.
export const MethodResponse = __t.enum("MethodResponse", {
  Success: __t.unit(),
  get Error() {
    return MethodError;
  },
  RpcError: __t.string(),
});
export type MethodResponse = __Infer<typeof MethodResponse>;

// The tagged union or sum type for the algebraic type `ModeConfig`.
export const ModeConfig = __t.enum("ModeConfig", {
  get Rounds() {
    return Rounds;
  },
  get ReverseCup() {
    return ReverseCup;
  },
  get TimeAttack() {
    return TimeAttack;
  },
  get RoundsBotOnline() {
    return RoundsBotOnline;
  },
});
export type ModeConfig = __Infer<typeof ModeConfig>;

// The tagged union or sum type for the algebraic type `MonitoringSettings`.
export const MonitoringSettings = __t.enum("MonitoringSettings", {
  get Club() {
    return MonitoringSettingsClub;
  },
  get Map() {
    return MonitoringSettingsMap;
  },
});
export type MonitoringSettings = __Infer<typeof MonitoringSettings>;

export const MonitoringSettingsClub = __t.object("MonitoringSettingsClub", {
  clubId: __t.string(),
});
export type MonitoringSettingsClub = __Infer<typeof MonitoringSettingsClub>;

export const MonitoringSettingsMap = __t.object("MonitoringSettingsMap", {
  mapUid: __t.string(),
});
export type MonitoringSettingsMap = __Infer<typeof MonitoringSettingsMap>;

export const MyProjectV1 = __t.object("MyProjectV1", {
  id: __t.u32(),
  creatorAccountId: __t.uuid(),
  creatorName: __t.string(),
  name: __t.string(),
  startingAt: __t.timestamp(),
  endingAt: __t.timestamp(),
  description: __t.string(),
  get status() {
    return ProjectStatus;
  },
});
export type MyProjectV1 = __Infer<typeof MyProjectV1>;

// The tagged union or sum type for the algebraic type `NodeKindHandle`.
export const NodeKindHandle = __t.enum("NodeKindHandle", {
  MatchV1: __t.u32(),
  CompetitionV1: __t.u32(),
  MonitoringV1: __t.u32(),
  ServerV1: __t.u32(),
  SchedulingV1: __t.u32(),
  PortalV1: __t.u32(),
  RegistrationV1: __t.u32(),
});
export type NodeKindHandle = __Infer<typeof NodeKindHandle>;

export const NodePositionUpdate = __t.object("NodePositionUpdate", {
  get node() {
    return NodeKindHandle;
  },
  get position() {
    return Vec2;
  },
});
export type NodePositionUpdate = __Infer<typeof NodePositionUpdate>;

export const Pause = __t.object("Pause", {
  available: __t.bool(),
  active: __t.bool(),
});
export type Pause = __Infer<typeof Pause>;

export const PermittedPlayer = __t.object("PermittedPlayer", {
  accountId: __t.uuid(),
  mandatory: __t.bool(),
  onlySpectator: __t.bool(),
});
export type PermittedPlayer = __Infer<typeof PermittedPlayer>;

export const PlayLoopEnd = __t.object("PlayLoopEnd", {
  count: __t.u32(),
  valid: __t.u32(),
  time: __t.u32(),
  isValid: __t.bool(),
});
export type PlayLoopEnd = __Infer<typeof PlayLoopEnd>;

export const PlayLoopStart = __t.object("PlayLoopStart", {
  count: __t.u32(),
  valid: __t.u32(),
  time: __t.u32(),
});
export type PlayLoopStart = __Infer<typeof PlayLoopStart>;

export const Player = __t.object("Player", {
  accountId: __t.string(),
  name: __t.string(),
  team: __t.i32(),
  rank: __t.u32(),
  roundPoints: __t.i32(),
  mapPoints: __t.i32(),
  matchPoints: __t.i32(),
  get bestRacetime() {
    return RoundTime;
  },
  bestRaceCheckpoints: __t.array(__t.u32()),
  get bestLaptime() {
    return RoundTime;
  },
  bestLapCheckpoints: __t.array(__t.u32()),
  get previousRacetime() {
    return RoundTime;
  },
  previousRaceCheckpoints: __t.array(__t.u32()),
});
export type Player = __Infer<typeof Player>;

// The tagged union or sum type for the algebraic type `PlayerAction`.
export const PlayerAction = __t.enum("PlayerAction", {
  GiveUp: __t.unit(),
  get Respawn() {
    return PlayerActionRespawn;
  },
  get Checkpoint() {
    return PlayerActionCheckpoint;
  },
});
export type PlayerAction = __Infer<typeof PlayerAction>;

export const PlayerActionCheckpoint = __t.object("PlayerActionCheckpoint", {
  speed: __t.f32(),
  time: __t.u32(),
});
export type PlayerActionCheckpoint = __Infer<typeof PlayerActionCheckpoint>;

export const PlayerActionRespawn = __t.object("PlayerActionRespawn", {
  speed: __t.f32(),
  standing: __t.bool(),
});
export type PlayerActionRespawn = __Infer<typeof PlayerActionRespawn>;

export const PlayerChat = __t.object("PlayerChat", {
  accountId: __t.string(),
  text: __t.string(),
  isRegisteredCmd: __t.bool(),
  options: __t.i32(),
});
export type PlayerChat = __Infer<typeof PlayerChat>;

export const PlayerConnect = __t.object("PlayerConnect", {
  accountId: __t.string(),
  isSpectator: __t.bool(),
});
export type PlayerConnect = __Infer<typeof PlayerConnect>;

export const PlayerDisconnect = __t.object("PlayerDisconnect", {
  accountId: __t.string(),
  disconnectReason: __t.string(),
});
export type PlayerDisconnect = __Infer<typeof PlayerDisconnect>;

export const PlayerInfo = __t.object("PlayerInfo", {
  accountId: __t.string(),
  nickName: __t.string(),
  playerId: __t.i32(),
  teamId: __t.i32(),
  spectatorStatus: __t.i32(),
  ladderRanking: __t.i32(),
  flags: __t.i32(),
});
export type PlayerInfo = __Infer<typeof PlayerInfo>;

export const Podium = __t.object("Podium", {
  time: __t.u32(),
});
export type Podium = __Infer<typeof Podium>;

// The tagged union or sum type for the algebraic type `PointsLimit`.
export const PointsLimit = __t.enum("PointsLimit", {
  Unlimited: __t.unit(),
  PointsLimit: __t.u32(),
});
export type PointsLimit = __Infer<typeof PointsLimit>;

export const Portal = __t.object("Portal", {
  name: __t.string(),
  id: __t.u32(),
  parentId: __t.u32(),
  projectId: __t.u32(),
  targetId: __t.u32(),
  targetVariant: __t.u8(),
});
export type Portal = __Infer<typeof Portal>;

export const ProjectMember = __t.object("ProjectMember", {
  permissions: __t.u64(),
  id: __t.u32(),
  projectId: __t.u32(),
  accountId: __t.u32(),
});
export type ProjectMember = __Infer<typeof ProjectMember>;

export const ProjectRole = __t.object("ProjectRole", {
  name: __t.string(),
  id: __t.u32(),
  projectId: __t.u32(),
  permissions: __t.u64(),
});
export type ProjectRole = __Infer<typeof ProjectRole>;

export const ProjectRoleMember = __t.object("ProjectRoleMember", {
  roleId: __t.u32(),
  accountId: __t.u32(),
});
export type ProjectRoleMember = __Infer<typeof ProjectRoleMember>;

export const ProjectServer = __t.object("ProjectServer", {
  projectId: __t.u32(),
  serverId: __t.u32(),
});
export type ProjectServer = __Infer<typeof ProjectServer>;

// The tagged union or sum type for the algebraic type `ProjectStatus`.
export const ProjectStatus = __t.enum("ProjectStatus", {
  Planning: __t.unit(),
  Announced: __t.unit(),
  Ongoing: __t.unit(),
  Ended: __t.unit(),
});
export type ProjectStatus = __Infer<typeof ProjectStatus>;

export const ProjectStatusScheduleV1 = __t.object("ProjectStatusScheduleV1", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  projectId: __t.u32(),
  get newStatus() {
    return ProjectStatus;
  },
});
export type ProjectStatusScheduleV1 = __Infer<typeof ProjectStatusScheduleV1>;

export const ProjectV1 = __t.object("ProjectV1", {
  name: __t.string(),
  description: __t.string(),
  creatorAccountId: __t.uuid(),
  startingAt: __t.timestamp(),
  endingAt: __t.timestamp(),
  id: __t.u32(),
  get status() {
    return ProjectStatus;
  },
});
export type ProjectV1 = __Infer<typeof ProjectV1>;

export const RawServerConfig = __t.object("RawServerConfig", {
  id: __t.u32(),
  get config() {
    return ServerConfig;
  },
});
export type RawServerConfig = __Infer<typeof RawServerConfig>;

export const RawServerMethodCall = __t.object("RawServerMethodCall", {
  id: __t.u32(),
  serverId: __t.u32(),
  accountId: __t.uuid(),
  timestamp: __t.timestamp(),
  get call() {
    return MethodCall;
  },
});
export type RawServerMethodCall = __Infer<typeof RawServerMethodCall>;

export const RawServerOccupation = __t.object("RawServerOccupation", {
  serverId: __t.u32(),
  matchId: __t.u32(),
});
export type RawServerOccupation = __Infer<typeof RawServerOccupation>;

export const RawServerPlayer = __t.object("RawServerPlayer", {
  accountId: __t.uuid(),
  serverId: __t.u32(),
  spectator: __t.bool(),
});
export type RawServerPlayer = __Infer<typeof RawServerPlayer>;

export const RawServerV1 = __t.object("RawServerV1", {
  identity: __t.identity(),
  serverLogin: __t.string(),
  accountId: __t.uuid(),
  id: __t.u32(),
  online: __t.bool(),
  capturable: __t.bool(),
  verified: __t.bool(),
});
export type RawServerV1 = __Infer<typeof RawServerV1>;

export const RegisteredPlayer = __t.object("RegisteredPlayer", {
  registrationId: __t.u32(),
  accountId: __t.uuid(),
  registeredAt: __t.timestamp(),
});
export type RegisteredPlayer = __Infer<typeof RegisteredPlayer>;

export const RegisteredTeam = __t.object("RegisteredTeam", {
  name: __t.string(),
  accountId: __t.uuid(),
  registeredAt: __t.timestamp(),
  competitionId: __t.u32(),
  id: __t.u32(),
});
export type RegisteredTeam = __Infer<typeof RegisteredTeam>;

export const Registration = __t.object("Registration", {
  name: __t.string(),
  id: __t.u32(),
  parentId: __t.u32(),
  projectId: __t.u32(),
  get settings() {
    return RegistrationSettings;
  },
});
export type Registration = __Infer<typeof Registration>;

export const RegistrationPlayerSettings = __t.object("RegistrationPlayerSettings", {
  playerLimit: __t.option(__t.u32()),
  registrationDeadline: __t.timestamp(),
});
export type RegistrationPlayerSettings = __Infer<typeof RegistrationPlayerSettings>;

// The tagged union or sum type for the algebraic type `RegistrationSettings`.
export const RegistrationSettings = __t.enum("RegistrationSettings", {
  get Players() {
    return RegistrationPlayerSettings;
  },
  get Team() {
    return RegistrationTeamSettings;
  },
  None: __t.unit(),
});
export type RegistrationSettings = __Infer<typeof RegistrationSettings>;

export const RegistrationTeamSettings = __t.object("RegistrationTeamSettings", {
  teamLimit: __t.option(__t.u32()),
  teamSizeMin: __t.u8(),
  teamSizeMax: __t.u8(),
  registrationDeadline: __t.timestamp(),
});
export type RegistrationTeamSettings = __Infer<typeof RegistrationTeamSettings>;

export const Respawn = __t.object("Respawn", {
  accountId: __t.string(),
  time: __t.u32(),
  numberRespawns: __t.u32(),
  racetime: __t.i32(),
  laptime: __t.i32(),
  checkpointInRace: __t.i32(),
  checkpointInLap: __t.i32(),
  speed: __t.f32(),
});
export type Respawn = __Infer<typeof Respawn>;

// The tagged union or sum type for the algebraic type `RespawnBehaviour`.
export const RespawnBehaviour = __t.enum("RespawnBehaviour", {
  Default: __t.unit(),
  TimeAttack: __t.unit(),
  Ignore: __t.unit(),
  GiveUpAtStart: __t.unit(),
  GiveUpAlways: __t.unit(),
  GiveUpNever: __t.unit(),
});
export type RespawnBehaviour = __Infer<typeof RespawnBehaviour>;

export const ReverseCup = __t.object("ReverseCup", {
  get finishTimeout() {
    return FinishTimeout;
  },
  get mapsPerMatch() {
    return MapsPerMatch;
  },
  useCustomPointsRepartition: __t.bool(),
  pointsRepartition: __t.array(__t.u32()),
  get roundsPerMap() {
    return RoundsPerMap;
  },
  useTieBreaker: __t.bool(),
  startingPoints: __t.i32(),
  disableLastChance: __t.bool(),
  allowFastForwardRounds: __t.bool(),
  fastForwardPointsRepartition: __t.bool(),
  dnfPointsLoss: __t.u32(),
  get lastChanceDnfMode() {
    return LastChanceDnfMode;
  },
  numberOfPlayers: __t.u32(),
});
export type ReverseCup = __Infer<typeof ReverseCup>;

// The tagged union or sum type for the algebraic type `RoundTime`.
export const RoundTime = __t.enum("RoundTime", {
  None: __t.unit(),
  Time: __t.u32(),
});
export type RoundTime = __Infer<typeof RoundTime>;

export const Rounds = __t.object("Rounds", {
  get finishTimeout() {
    return FinishTimeout;
  },
  get mapsPerMatch() {
    return MapsPerMatch;
  },
  get pointsLimit() {
    return PointsLimit;
  },
  useCustomPointsRepartition: __t.bool(),
  pointsRepartition: __t.array(__t.u32()),
  get roundsPerMap() {
    return RoundsPerMap;
  },
  useTieBreaker: __t.bool(),
});
export type Rounds = __Infer<typeof Rounds>;

export const RoundsBotOnline = __t.object("RoundsBotOnline", {});
export type RoundsBotOnline = __Infer<typeof RoundsBotOnline>;

// The tagged union or sum type for the algebraic type `RoundsPerMap`.
export const RoundsPerMap = __t.enum("RoundsPerMap", {
  Unlimited: __t.unit(),
  Rounds: __t.u32(),
});
export type RoundsPerMap = __Infer<typeof RoundsPerMap>;

export const ScheduleV1 = __t.object("ScheduleV1", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  competitionId: __t.u32(),
  projectId: __t.u32(),
});
export type ScheduleV1 = __Infer<typeof ScheduleV1>;

export const Scores = __t.object("Scores", {
  responseId: __t.string(),
  section: __t.string(),
  useTeams: __t.bool(),
  winnerTeam: __t.i32(),
  winnerPlayer: __t.string(),
  get teams() {
    return __t.array(Team);
  },
  get players() {
    return __t.array(Player);
  },
});
export type Scores = __Infer<typeof Scores>;

export const ServerConfig = __t.object("ServerConfig", {
  get options() {
    return ServerOptions;
  },
  get common() {
    return Common;
  },
  get mode() {
    return ModeConfig;
  },
  get maps() {
    return MapPoolConfig;
  },
});
export type ServerConfig = __Infer<typeof ServerConfig>;

export const ServerOptions = __t.object("ServerOptions", {});
export type ServerOptions = __Infer<typeof ServerOptions>;

export const StartLine = __t.object("StartLine", {
  accountId: __t.string(),
  time: __t.u32(),
});
export type StartLine = __Infer<typeof StartLine>;

export const StartMap = __t.object("StartMap", {
  count: __t.u32(),
  valid: __t.u32(),
  restarted: __t.bool(),
  time: __t.u32(),
  get map() {
    return Map;
  },
});
export type StartMap = __Infer<typeof StartMap>;

export const StartMatch = __t.object("StartMatch", {
  count: __t.u32(),
  time: __t.u32(),
});
export type StartMatch = __Infer<typeof StartMatch>;

export const StartRound = __t.object("StartRound", {
  count: __t.u32(),
  time: __t.u32(),
});
export type StartRound = __Infer<typeof StartRound>;

export const StartServer = __t.object("StartServer", {
  restarted: __t.bool(),
  time: __t.u32(),
});
export type StartServer = __Infer<typeof StartServer>;

export const StartTurn = __t.object("StartTurn", {
  count: __t.u32(),
  valid: __t.u32(),
  time: __t.u32(),
});
export type StartTurn = __Infer<typeof StartTurn>;

export const TabCompetitionConnection = __t.object("TabCompetitionConnection", {
  id: __t.u32(),
  competitionId: __t.u32(),
  projectId: __t.u32(),
  connectionFrom: __t.u32(),
  connectionTo: __t.u32(),
  connectionFromVariant: __t.u8(),
  connectionToVariant: __t.u8(),
  get connectionSettings() {
    return ConnectionSettings;
  },
  resolved: __t.bool(),
});
export type TabCompetitionConnection = __Infer<typeof TabCompetitionConnection>;

export const TabCompetitionNodePosition = __t.object("TabCompetitionNodePosition", {
  get position() {
    return Vec2;
  },
  id: __t.u32(),
  competitionId: __t.u32(),
  nodeId: __t.u32(),
  nodeVariant: __t.u8(),
});
export type TabCompetitionNodePosition = __Infer<typeof TabCompetitionNodePosition>;

export const Team = __t.object("Team", {
  id: __t.u32(),
  name: __t.string(),
  roundPoints: __t.u32(),
  mapPoints: __t.u32(),
  matchPoints: __t.u32(),
});
export type Team = __Infer<typeof Team>;

export const TimeAttack = __t.object("TimeAttack", {
  timeLimit: __t.i32(),
});
export type TimeAttack = __Infer<typeof TimeAttack>;

export const TmCompRecord = __t.object("TmCompRecord", {
  matchId: __t.u32(),
  mapUid: __t.string(),
  accountId: __t.uuid(),
  timestamp: __t.timestamp(),
  time: __t.u32(),
});
export type TmCompRecord = __Infer<typeof TmCompRecord>;

export const TmMapRecord = __t.object("TmMapRecord", {
  id: __t.u32(),
  mapUid: __t.string(),
  accountId: __t.uuid(),
  timestamp: __t.timestamp(),
  time: __t.u32(),
});
export type TmMapRecord = __Infer<typeof TmMapRecord>;

export const TmMatchEvent = __t.object("TmMatchEvent", {
  matchId: __t.u32(),
  get event() {
    return Event;
  },
});
export type TmMatchEvent = __Infer<typeof TmMatchEvent>;

export const TmMatchRoundPlayer = __t.object("TmMatchRoundPlayer", {
  internalAccountId: __t.u32(),
  matchId: __t.u32(),
  time: __t.i32(),
  roundPoints: __t.i32(),
  round: __t.u16(),
});
export type TmMatchRoundPlayer = __Infer<typeof TmMatchRoundPlayer>;

export const TmMatchRoundPlayerExt = __t.object("TmMatchRoundPlayerExt", {
  get roundActions() {
    return __t.array(PlayerAction);
  },
  internalAccountId: __t.u32(),
  matchId: __t.u32(),
  round: __t.u16(),
  id: __t.u32(),
});
export type TmMatchRoundPlayerExt = __Infer<typeof TmMatchRoundPlayerExt>;

export const TmMatchState = __t.object("TmMatchState", {
  mapId: __t.uuid(),
  matchId: __t.u32(),
  restarted: __t.u16(),
  round: __t.u16(),
  warmup: __t.u16(),
  isWarmup: __t.bool(),
  paused: __t.bool(),
});
export type TmMatchState = __Infer<typeof TmMatchState>;

export const TmMatchV1 = __t.object("TmMatchV1", {
  name: __t.string(),
  id: __t.u32(),
  projectId: __t.u32(),
  competitionId: __t.u32(),
  preMatchConfig: __t.u32(),
  matchConfig: __t.u32(),
  postMatchConfig: __t.u32(),
  get status() {
    return MatchStatus;
  },
  autoProvisionServer: __t.bool(),
});
export type TmMatchV1 = __Infer<typeof TmMatchV1>;

export const TmMonitoring = __t.object("TmMonitoring", {
  id: __t.u32(),
  project: __t.u32(),
  competition: __t.u32(),
  get settings() {
    return MonitoringSettings;
  },
  name: __t.option(__t.string()),
  active: __t.bool(),
});
export type TmMonitoring = __Infer<typeof TmMonitoring>;

export const TmRecord = __t.object("TmRecord", {
  accountId: __t.uuid(),
  ghost: __t.uuid(),
  mapUid: __t.string(),
  zone: __t.string(),
  playerName: __t.string(),
  timestamp: __t.timestamp(),
  time: __t.u32(),
});
export type TmRecord = __Infer<typeof TmRecord>;

export const TmServerMethodResponse = __t.object("TmServerMethodResponse", {
  id: __t.u32(),
  get response() {
    return MethodResponse;
  },
});
export type TmServerMethodResponse = __Infer<typeof TmServerMethodResponse>;

export const TmWorker = __t.object("TmWorker", {
  tmLogin: __t.string(),
  identity: __t.identity(),
  ownerId: __t.string(),
  online: __t.bool(),
});
export type TmWorker = __Infer<typeof TmWorker>;

export const TmWorkerJobs = __t.object("TmWorkerJobs", {
  tmLogin: __t.string(),
  mapUid: __t.string(),
});
export type TmWorkerJobs = __Infer<typeof TmWorkerJobs>;

export const UnloadingMapEnd = __t.object("UnloadingMapEnd", {
  time: __t.u32(),
});
export type UnloadingMapEnd = __Infer<typeof UnloadingMapEnd>;

export const UnloadingMapStart = __t.object("UnloadingMapStart", {
  time: __t.u32(),
  get map() {
    return Map;
  },
});
export type UnloadingMapStart = __Infer<typeof UnloadingMapStart>;

export const UserIdentity = __t.object("UserIdentity", {
  identity: __t.identity(),
  accountId: __t.uuid(),
});
export type UserIdentity = __Infer<typeof UserIdentity>;

export const UserV1 = __t.object("UserV1", {
  accountId: __t.uuid(),
  internalId: __t.u32(),
  name: __t.string(),
  clubTag: __t.string(),
  online: __t.bool(),
});
export type UserV1 = __Infer<typeof UserV1>;

export const Vec2 = __t.object("Vec2", {
  x: __t.f32(),
  y: __t.f32(),
});
export type Vec2 = __Infer<typeof Vec2>;

// The tagged union or sum type for the algebraic type `WarmupDuration`.
export const WarmupDuration = __t.enum("WarmupDuration", {
  OneTry: __t.unit(),
  BasedOnMedal: __t.unit(),
  Seconds: __t.u32(),
});
export type WarmupDuration = __Infer<typeof WarmupDuration>;

export const WarmupRound = __t.object("WarmupRound", {
  current: __t.u32(),
  total: __t.u32(),
});
export type WarmupRound = __Infer<typeof WarmupRound>;

// The tagged union or sum type for the algebraic type `WarmupTimeout`.
export const WarmupTimeout = __t.enum("WarmupTimeout", {
  BasedOnMedal: __t.unit(),
  Seconds: __t.u32(),
});
export type WarmupTimeout = __Infer<typeof WarmupTimeout>;

export const WayPoint = __t.object("WayPoint", {
  accountId: __t.string(),
  time: __t.u32(),
  racetime: __t.u32(),
  laptime: __t.u32(),
  speed: __t.f32(),
  checkpointInRace: __t.u32(),
  checkpointInLap: __t.u32(),
  isEndRace: __t.bool(),
  isEndLap: __t.bool(),
  isInfiniteLaps: __t.bool(),
  isIndependentLaps: __t.bool(),
  currentRaceCheckpoints: __t.array(__t.u32()),
  currentLapCheckpoints: __t.array(__t.u32()),
  blockId: __t.string(),
});
export type WayPoint = __Infer<typeof WayPoint>;

