// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("WayPoint", {
  accountId: __t.string(),
  time: __t.u32(),
  racetime: __t.u32(),
  laptime: __t.u32(),
  speed: __t.f32(),
  checkpointInRace: __t.u32(),
  checkpointInLap: __t.u32(),
  isEndRace: __t.bool(),
  isEndLap: __t.bool(),
  isInfiniteLaps: __t.bool(),
  isIndependentLaps: __t.bool(),
  currentRaceCheckpoints: __t.array(__t.u32()),
  currentLapCheckpoints: __t.array(__t.u32()),
  blockId: __t.string(),
});


