// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import CompetitionStatus from "./competition_status_type";
import Scheduling from "./scheduling_type";
import RegistrationRules from "./registration_rules_type";
import Competitions from "./competitions_type";


export default __t.object("Competition", {
  id: __t.u32(),
  tournamentId: __t.u32(),
  parentId: __t.option(__t.u32()),
  name: __t.string(),
  get status() {
    return CompetitionStatus;
  },
  estimate: __t.option(__t.timeDuration()),
  get scheduling() {
    return Scheduling;
  },
  get registrationRules() {
    return RegistrationRules;
  },
  entryPoints: __t.option(__t.array(__t.u32())),
  get competitions() {
    return Competitions;
  },
});


