// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("Map", {
  uid: __t.string(),
  name: __t.string(),
  filename: __t.string(),
  author: __t.string(),
  authorNickname: __t.string(),
  environment: __t.string(),
  mood: __t.string(),
  bronzeTime: __t.u32(),
  silverTime: __t.u32(),
  goldTime: __t.u32(),
  authorTime: __t.u32(),
  copperprice: __t.u32(),
  lapRace: __t.bool(),
  numberLaps: __t.u32(),
  mapType: __t.string(),
  mapStyle: __t.string(),
});


