// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import MonitoringSettingsClub from "./monitoring_settings_club_type";
import MonitoringSettingsMap from "./monitoring_settings_map_type";


// The tagged union or sum type for the algebraic type `MonitoringSettings`.
const MonitoringSettings = __t.enum("MonitoringSettings", {get Club() {
    return MonitoringSettingsClub;
  },
  get Map() {
    return MonitoringSettingsMap;
  },
});

export default MonitoringSettings;


