// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import RoundTime from "./round_time_type";


export default __t.object("Player", {
  login: __t.string(),
  accountId: __t.string(),
  name: __t.string(),
  team: __t.i32(),
  rank: __t.u32(),
  roundPoints: __t.u32(),
  mapPoints: __t.u32(),
  matchPoints: __t.u32(),
  get bestRacetime() {
    return RoundTime;
  },
  bestRaceCheckpoints: __t.array(__t.u32()),
  get bestLaptime() {
    return RoundTime;
  },
  bestLapCheckpoints: __t.array(__t.u32()),
  get previousRacetime() {
    return RoundTime;
  },
  previousRaceCheckpoints: __t.array(__t.u32()),
});


