// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import ServerConfig from "./server_config_type";
import ServerState from "./server_state_type";


export default __t.object("TmServer", {
  id: __t.string(),
  identity: __t.identity(),
  ownerId: __t.string(),
  online: __t.bool(),
  get config() {
    return ServerConfig;
  },
  get state() {
    return ServerState;
  },
  capturable: __t.bool(),
  activeMatch: __t.option(__t.u32()),
});


