// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  NodeKindHandle,
  ConnectionType,
  ConnectionStatus,
} from "./types";


export default __t.row({
  id: __t.u32(),
  get origin() {
    return NodeKindHandle;
  },
  get target() {
    return NodeKindHandle;
  },
  get connectionType() {
    return ConnectionType.name("connection_type");
  },
  get status() {
    return ConnectionStatus;
  },
});
