// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity(),
  serverLogin: __t.string().name("server_login"),
  serverAccountId: __t.uuid().name("server_account_id"),
  userId: __t.u32().name("user_id"),
  id: __t.u32(),
  online: __t.bool(),
  capturable: __t.bool(),
  verified: __t.bool(),
});
