// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.1 (commit 3d7607082ab47257adeb7c25164536511237f2b5).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import CompetitionConnectionDataUpdateReducer from "./competition_connection_data_update_reducer";
import CompetitionCreateReducer from "./competition_create_reducer";
import CompetitionNodePositionUpdateReducer from "./competition_node_position_update_reducer";
import CompetitionNodePositionsUpdateReducer from "./competition_node_positions_update_reducer";
import CompetitionTemplateCreateReducer from "./competition_template_create_reducer";
import ConnectionActionUpdateReducer from "./connection_action_update_reducer";
import ConnectionConfiguredReducer from "./connection_configured_reducer";
import ConnectionCreateReducer from "./connection_create_reducer";
import ConnectionDeleteReducer from "./connection_delete_reducer";
import CreateProjectReducer from "./create_project_reducer";
import InputCreateReducer from "./input_create_reducer";
import InputTemplateCreateReducer from "./input_template_create_reducer";
import LeaderboardConfiguredReducer from "./leaderboard_configured_reducer";
import LeaderboardCreateReducer from "./leaderboard_create_reducer";
import LeaderboardSettingsUpdateReducer from "./leaderboard_settings_update_reducer";
import LeaderboardTemplateCreateReducer from "./leaderboard_template_create_reducer";
import LendRawServerReducer from "./lend_raw_server_reducer";
import MatchAssignServerReducer from "./match_assign_server_reducer";
import MatchConfiguredReducer from "./match_configured_reducer";
import MatchCreateReducer from "./match_create_reducer";
import MatchEndReducer from "./match_end_reducer";
import MatchManualRecoveryReducer from "./match_manual_recovery_reducer";
import MatchOpenReducer from "./match_open_reducer";
import MatchOverrideConfigReducer from "./match_override_config_reducer";
import MatchOverridePreConfigReducer from "./match_override_pre_config_reducer";
import MatchRestartReducer from "./match_restart_reducer";
import MatchRoundPlayerSetPositionManualReducer from "./match_round_player_set_position_manual_reducer";
import MatchRoundPlayerSetScoreManualReducer from "./match_round_player_set_score_manual_reducer";
import MatchServerRevokeReducer from "./match_server_revoke_reducer";
import MatchSetPreparationReducer from "./match_set_preparation_reducer";
import MatchSharedConfigReducer from "./match_shared_config_reducer";
import MatchSharedPreConfigReducer from "./match_shared_pre_config_reducer";
import MatchTemplateCreateReducer from "./match_template_create_reducer";
import MatchTryStartReducer from "./match_try_start_reducer";
import MemberAddReducer from "./member_add_reducer";
import MemberAssignPermissionReducer from "./member_assign_permission_reducer";
import MemberRemoveReducer from "./member_remove_reducer";
import MigrationLeaderboardToV2Reducer from "./migration_leaderboard_to_v_2_reducer";
import MigrationRawServerConfigToV2Reducer from "./migration_raw_server_config_to_v_2_reducer";
import NodeDeleteReducer from "./node_delete_reducer";
import NodeNameEditReducer from "./node_name_edit_reducer";
import OutputCreateReducer from "./output_create_reducer";
import PostEventReducer from "./post_event_reducer";
import ProjectEditDatesReducer from "./project_edit_dates_reducer";
import ProjectEditDescriptionReducer from "./project_edit_description_reducer";
import ProjectEditNameReducer from "./project_edit_name_reducer";
import ProjectUpdateStatusReducer from "./project_update_status_reducer";
import RawServerConfigSharedNewReducer from "./raw_server_config_shared_new_reducer";
import RawServerConfigSharedUpdateReducer from "./raw_server_config_shared_update_reducer";
import RawServerPlayerAddReducer from "./raw_server_player_add_reducer";
import RawServerVerifyReducer from "./raw_server_verify_reducer";
import RegisterPlayerReducer from "./register_player_reducer";
import RegistrationConfiguredReducer from "./registration_configured_reducer";
import RegistrationCreateReducer from "./registration_create_reducer";
import RegistrationEndReducer from "./registration_end_reducer";
import RegistrationSettingsUpdateReducer from "./registration_settings_update_reducer";
import RegistrationStartReducer from "./registration_start_reducer";
import RegistrationTemplateCreateReducer from "./registration_template_create_reducer";
import RevokeRawServerReducer from "./revoke_raw_server_reducer";
import RoleAssignPermissionReducer from "./role_assign_permission_reducer";
import RoleCreateReducer from "./role_create_reducer";
import RoleMemberAssignReducer from "./role_member_assign_reducer";
import RoleMemberRemoveReducer from "./role_member_remove_reducer";
import RoleRemoveReducer from "./role_remove_reducer";
import ScheduleConfiguredReducer from "./schedule_configured_reducer";
import ScheduleCreateReducer from "./schedule_create_reducer";
import ScheduleManualRunReducer from "./schedule_manual_run_reducer";
import ScheduleSettingsUpdateReducer from "./schedule_settings_update_reducer";
import ServerAssignRawServerReducer from "./server_assign_raw_server_reducer";
import ServerConfigOverrideReducer from "./server_config_override_reducer";
import ServerConfiguredReducer from "./server_configured_reducer";
import ServerConfiguringReducer from "./server_configuring_reducer";
import ServerCreateReducer from "./server_create_reducer";
import ServerMethodCallReducer from "./server_method_call_reducer";
import ServerMethodResponseReducer from "./server_method_response_reducer";
import ServerRemoveRawServerReducer from "./server_remove_raw_server_reducer";
import ServerTemplateCreateReducer from "./server_template_create_reducer";
import SetEnvVarReducer from "./set_env_var_reducer";
import UnregisterPlayerReducer from "./unregister_player_reducer";
import UnstableManualRegisterOverridePlayersReducer from "./unstable_manual_register_override_players_reducer";
import UnstableMatchChatMessageReducer from "./unstable_match_chat_message_reducer";
import UnstableRawServerConfigUpdateMapsReducer from "./unstable_raw_server_config_update_maps_reducer";

// Import all procedure arg schemas
import * as LoginAsServerProcedure from "./login_as_server_procedure";
import * as MatchRoundReplayProcedure from "./match_round_replay_procedure";
import * as NodeLeaderboardInputProcedure from "./node_leaderboard_input_procedure";
import * as NodeLeaderboardInputFinalizeProcedure from "./node_leaderboard_input_finalize_procedure";
import * as NodeLeaderboardOutputProcedure from "./node_leaderboard_output_procedure";
import * as NodeLeaderboardOutputRawProcedure from "./node_leaderboard_output_raw_procedure";
import * as PostRoundReplayProcedure from "./post_round_replay_procedure";
import * as TestNodePermittedPlayersInputProcedure from "./test_node_permitted_players_input_procedure";
import * as UnstableCompetitionProcedure from "./unstable_competition_procedure";

// Import all table schema definitions
import CompetitionAvailableServerPoolRow from "./competition_available_server_pool_table";
import EventRawServerMethodRow from "./event_raw_server_method_table";
import EventRawServerStateRow from "./event_raw_server_state_table";
import MatchStateRow from "./match_state_table";
import MyNodePositionsRow from "./my_node_positions_table";
import MyProjectsRow from "./my_projects_table";
import MyUserRow from "./my_user_table";
import ProjectCompetitionDescendantsRow from "./project_competition_descendants_table";
import RawServerPermittedPlayersRow from "./raw_server_permitted_players_table";
import RawServerPlayerDestinationRow from "./raw_server_player_destination_table";
import TabMatchRow from "./tab_match_table";
import TabMatchChatRow from "./tab_match_chat_table";
import TabMatchRoundPlayerRow from "./tab_match_round_player_table";
import TabMatchRoundPlayerExtRow from "./tab_match_round_player_ext_table";
import TabRawServerRow from "./tab_raw_server_table";
import TabRawServerOccupationRow from "./tab_raw_server_occupation_table";
import TabRawServerPlayerRow from "./tab_raw_server_player_table";
import TabRegisterationPlayerRow from "./tab_registeration_player_table";
import TabRegistrationRow from "./tab_registration_table";
import TabUserRow from "./tab_user_table";
import UnstableCompetitionConnectionRow from "./unstable_competition_connection_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  eventRawServerMethod: __table({
    name: 'event_raw_server_method',
    indexes: [
      { accessor: 'id', name: 'event_raw_server_method_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'server_id', name: 'event_raw_server_method_server_id_idx_hash', algorithm: 'btree', columns: [
        'serverId',
      ] },
    ],
    constraints: [
      { name: 'event_raw_server_method_id_key', constraint: 'unique', columns: ['id'] },
    ],
    event: true,
  }, EventRawServerMethodRow),
  eventRawServerState: __table({
    name: 'event_raw_server_state',
    indexes: [
      { accessor: 'server_id', name: 'event_raw_server_state_server_id_idx_btree', algorithm: 'btree', columns: [
        'serverId',
      ] },
    ],
    constraints: [
      { name: 'event_raw_server_state_server_id_key', constraint: 'unique', columns: ['serverId'] },
    ],
    event: true,
  }, EventRawServerStateRow),
  tabMatch: __table({
    name: 'tab_match',
    indexes: [
      { accessor: 'config', name: 'tab_match_config_idx_hash', algorithm: 'btree', columns: [
        'config',
      ] },
      { accessor: 'id', name: 'tab_match_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'parent_id', name: 'tab_match_parent_id_idx_hash', algorithm: 'btree', columns: [
        'parentId',
      ] },
      { accessor: 'pre_config', name: 'tab_match_pre_config_idx_hash', algorithm: 'btree', columns: [
        'preConfig',
      ] },
    ],
    constraints: [
      { name: 'tab_match_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TabMatchRow),
  tabMatchChat: __table({
    name: 'tab_match_chat',
    indexes: [
      { accessor: 'id', name: 'tab_match_chat_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'match_id', name: 'tab_match_chat_match_id_idx_hash', algorithm: 'btree', columns: [
        'matchId',
      ] },
      { accessor: 'user_id', name: 'tab_match_chat_user_id_idx_hash', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'tab_match_chat_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TabMatchChatRow),
  tabMatchRoundPlayer: __table({
    name: 'tab_match_round_player',
    indexes: [
      { accessor: 'id', name: 'tab_match_round_player_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'match_id', name: 'tab_match_round_player_match_id_idx_hash', algorithm: 'btree', columns: [
        'matchId',
      ] },
      { accessor: 'match_round_range', name: 'tab_match_round_player_match_id_round_idx_btree', algorithm: 'btree', columns: [
        'matchId',
        'round',
      ] },
      { accessor: 'match_round', name: 'tab_match_round_player_match_id_round_idx_hash', algorithm: 'btree', columns: [
        'matchId',
        'round',
      ] },
      { accessor: 'match_round_player', name: 'tab_match_round_player_match_id_round_user_id_idx_hash', algorithm: 'btree', columns: [
        'matchId',
        'round',
        'userId',
      ] },
      { accessor: 'user_id', name: 'tab_match_round_player_user_id_idx_hash', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'tab_match_round_player_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TabMatchRoundPlayerRow),
  tabMatchRoundPlayerExt: __table({
    name: 'tab_match_round_player_ext',
    indexes: [
      { accessor: 'id', name: 'tab_match_round_player_ext_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'match_id', name: 'tab_match_round_player_ext_match_id_idx_hash', algorithm: 'btree', columns: [
        'matchId',
      ] },
      { accessor: 'match_round_range', name: 'tab_match_round_player_ext_match_id_round_idx_btree', algorithm: 'btree', columns: [
        'matchId',
        'round',
      ] },
      { accessor: 'match_round', name: 'tab_match_round_player_ext_match_id_round_idx_hash', algorithm: 'btree', columns: [
        'matchId',
        'round',
      ] },
      { accessor: 'match_round_player', name: 'tab_match_round_player_ext_match_id_round_user_id_idx_hash', algorithm: 'btree', columns: [
        'matchId',
        'round',
        'userId',
      ] },
    ],
    constraints: [
      { name: 'tab_match_round_player_ext_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TabMatchRoundPlayerExtRow),
  tabRawServer: __table({
    name: 'tab_raw_server',
    indexes: [
      { accessor: 'id', name: 'tab_raw_server_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'server_login', name: 'tab_raw_server_server_login_idx_btree', algorithm: 'btree', columns: [
        'serverLogin',
      ] },
      { accessor: 'user_id', name: 'tab_raw_server_user_id_idx_hash', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'tab_raw_server_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'tab_raw_server_server_login_key', constraint: 'unique', columns: ['serverLogin'] },
    ],
  }, TabRawServerRow),
  tabRawServerOccupation: __table({
    name: 'tab_raw_server_occupation',
    indexes: [
      { accessor: 'node_handle', name: 'tab_raw_server_occupation_node_variant_node_id_idx_hash', algorithm: 'btree', columns: [
        'nodeVariant',
        'nodeId',
      ] },
      { accessor: 'server_id', name: 'tab_raw_server_occupation_server_id_idx_btree', algorithm: 'btree', columns: [
        'serverId',
      ] },
    ],
    constraints: [
      { name: 'tab_raw_server_occupation_server_id_key', constraint: 'unique', columns: ['serverId'] },
    ],
  }, TabRawServerOccupationRow),
  tabRawServerPlayer: __table({
    name: 'tab_raw_server_player',
    indexes: [
      { accessor: 'account_id', name: 'tab_raw_server_player_account_id_idx_btree', algorithm: 'btree', columns: [
        'accountId',
      ] },
      { accessor: 'server_id', name: 'tab_raw_server_player_server_id_idx_hash', algorithm: 'btree', columns: [
        'serverId',
      ] },
    ],
    constraints: [
      { name: 'tab_raw_server_player_account_id_key', constraint: 'unique', columns: ['accountId'] },
    ],
  }, TabRawServerPlayerRow),
  tabRegisterationPlayer: __table({
    name: 'tab_registeration_player',
    indexes: [
      { accessor: 'registration_id', name: 'tab_registeration_player_registration_id_idx_hash', algorithm: 'btree', columns: [
        'registrationId',
      ] },
      { accessor: 'user_registered', name: 'tab_registeration_player_user_id_registration_id_idx_hash', algorithm: 'btree', columns: [
        'userId',
        'registrationId',
      ] },
    ],
    constraints: [
    ],
  }, TabRegisterationPlayerRow),
  tabRegistration: __table({
    name: 'tab_registration',
    indexes: [
      { accessor: 'id', name: 'tab_registration_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'parent_id', name: 'tab_registration_parent_id_idx_hash', algorithm: 'btree', columns: [
        'parentId',
      ] },
    ],
    constraints: [
      { name: 'tab_registration_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TabRegistrationRow),
  tabUser: __table({
    name: 'tab_user',
    indexes: [
      { accessor: 'account_id', name: 'tab_user_account_id_idx_btree', algorithm: 'btree', columns: [
        'accountId',
      ] },
      { accessor: 'id', name: 'tab_user_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'tab_user_account_id_key', constraint: 'unique', columns: ['accountId'] },
      { name: 'tab_user_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TabUserRow),
  competitionAvailableServerPool: __table({
    name: 'competition_available_server_pool',
    indexes: [
    ],
    constraints: [
    ],
  }, CompetitionAvailableServerPoolRow),
  matchState: __table({
    name: 'match_state',
    indexes: [
    ],
    constraints: [
    ],
  }, MatchStateRow),
  myNodePositions: __table({
    name: 'my_node_positions',
    indexes: [
    ],
    constraints: [
    ],
  }, MyNodePositionsRow),
  myProjects: __table({
    name: 'my_projects',
    indexes: [
    ],
    constraints: [
    ],
  }, MyProjectsRow),
  myUser: __table({
    name: 'my_user',
    indexes: [
    ],
    constraints: [
    ],
  }, MyUserRow),
  projectCompetitionDescendants: __table({
    name: 'project_competition_descendants',
    indexes: [
    ],
    constraints: [
    ],
  }, ProjectCompetitionDescendantsRow),
  rawServerPermittedPlayers: __table({
    name: 'raw_server_permitted_players',
    indexes: [
    ],
    constraints: [
    ],
  }, RawServerPermittedPlayersRow),
  rawServerPlayerDestination: __table({
    name: 'raw_server_player_destination',
    indexes: [
    ],
    constraints: [
    ],
  }, RawServerPlayerDestinationRow),
  unstableCompetitionConnection: __table({
    name: 'unstable_competition_connection',
    indexes: [
    ],
    constraints: [
    ],
  }, UnstableCompetitionConnectionRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("competition_connection_data_update", CompetitionConnectionDataUpdateReducer),
  __reducerSchema("competition_create", CompetitionCreateReducer),
  __reducerSchema("competition_node_position_update", CompetitionNodePositionUpdateReducer),
  __reducerSchema("competition_node_positions_update", CompetitionNodePositionsUpdateReducer),
  __reducerSchema("competition_template_create", CompetitionTemplateCreateReducer),
  __reducerSchema("connection_action_update", ConnectionActionUpdateReducer),
  __reducerSchema("connection_configured", ConnectionConfiguredReducer),
  __reducerSchema("connection_create", ConnectionCreateReducer),
  __reducerSchema("connection_delete", ConnectionDeleteReducer),
  __reducerSchema("create_project", CreateProjectReducer),
  __reducerSchema("input_create", InputCreateReducer),
  __reducerSchema("input_template_create", InputTemplateCreateReducer),
  __reducerSchema("leaderboard_configured", LeaderboardConfiguredReducer),
  __reducerSchema("leaderboard_create", LeaderboardCreateReducer),
  __reducerSchema("leaderboard_settings_update", LeaderboardSettingsUpdateReducer),
  __reducerSchema("leaderboard_template_create", LeaderboardTemplateCreateReducer),
  __reducerSchema("lend_raw_server", LendRawServerReducer),
  __reducerSchema("match_assign_server", MatchAssignServerReducer),
  __reducerSchema("match_configured", MatchConfiguredReducer),
  __reducerSchema("match_create", MatchCreateReducer),
  __reducerSchema("match_end", MatchEndReducer),
  __reducerSchema("match_manual_recovery", MatchManualRecoveryReducer),
  __reducerSchema("match_open", MatchOpenReducer),
  __reducerSchema("match_override_config", MatchOverrideConfigReducer),
  __reducerSchema("match_override_pre_config", MatchOverridePreConfigReducer),
  __reducerSchema("match_restart", MatchRestartReducer),
  __reducerSchema("match_round_player_set_position_manual", MatchRoundPlayerSetPositionManualReducer),
  __reducerSchema("match_round_player_set_score_manual", MatchRoundPlayerSetScoreManualReducer),
  __reducerSchema("match_server_revoke", MatchServerRevokeReducer),
  __reducerSchema("match_set_preparation", MatchSetPreparationReducer),
  __reducerSchema("match_shared_config", MatchSharedConfigReducer),
  __reducerSchema("match_shared_pre_config", MatchSharedPreConfigReducer),
  __reducerSchema("match_template_create", MatchTemplateCreateReducer),
  __reducerSchema("match_try_start", MatchTryStartReducer),
  __reducerSchema("member_add", MemberAddReducer),
  __reducerSchema("member_assign_permission", MemberAssignPermissionReducer),
  __reducerSchema("member_remove", MemberRemoveReducer),
  __reducerSchema("migration_leaderboard_to_v2", MigrationLeaderboardToV2Reducer),
  __reducerSchema("migration_raw_server_config_to_v2", MigrationRawServerConfigToV2Reducer),
  __reducerSchema("node_delete", NodeDeleteReducer),
  __reducerSchema("node_name_edit", NodeNameEditReducer),
  __reducerSchema("output_create", OutputCreateReducer),
  __reducerSchema("post_event", PostEventReducer),
  __reducerSchema("project_edit_dates", ProjectEditDatesReducer),
  __reducerSchema("project_edit_description", ProjectEditDescriptionReducer),
  __reducerSchema("project_edit_name", ProjectEditNameReducer),
  __reducerSchema("project_update_status", ProjectUpdateStatusReducer),
  __reducerSchema("raw_server_config_shared_new", RawServerConfigSharedNewReducer),
  __reducerSchema("raw_server_config_shared_update", RawServerConfigSharedUpdateReducer),
  __reducerSchema("raw_server_player_add", RawServerPlayerAddReducer),
  __reducerSchema("raw_server_verify", RawServerVerifyReducer),
  __reducerSchema("register_player", RegisterPlayerReducer),
  __reducerSchema("registration_configured", RegistrationConfiguredReducer),
  __reducerSchema("registration_create", RegistrationCreateReducer),
  __reducerSchema("registration_end", RegistrationEndReducer),
  __reducerSchema("registration_settings_update", RegistrationSettingsUpdateReducer),
  __reducerSchema("registration_start", RegistrationStartReducer),
  __reducerSchema("registration_template_create", RegistrationTemplateCreateReducer),
  __reducerSchema("revoke_raw_server", RevokeRawServerReducer),
  __reducerSchema("role_assign_permission", RoleAssignPermissionReducer),
  __reducerSchema("role_create", RoleCreateReducer),
  __reducerSchema("role_member_assign", RoleMemberAssignReducer),
  __reducerSchema("role_member_remove", RoleMemberRemoveReducer),
  __reducerSchema("role_remove", RoleRemoveReducer),
  __reducerSchema("schedule_configured", ScheduleConfiguredReducer),
  __reducerSchema("schedule_create", ScheduleCreateReducer),
  __reducerSchema("schedule_manual_run", ScheduleManualRunReducer),
  __reducerSchema("schedule_settings_update", ScheduleSettingsUpdateReducer),
  __reducerSchema("server_assign_raw_server", ServerAssignRawServerReducer),
  __reducerSchema("server_config_override", ServerConfigOverrideReducer),
  __reducerSchema("server_configured", ServerConfiguredReducer),
  __reducerSchema("server_configuring", ServerConfiguringReducer),
  __reducerSchema("server_create", ServerCreateReducer),
  __reducerSchema("server_method_call", ServerMethodCallReducer),
  __reducerSchema("server_method_response", ServerMethodResponseReducer),
  __reducerSchema("server_remove_raw_server", ServerRemoveRawServerReducer),
  __reducerSchema("server_template_create", ServerTemplateCreateReducer),
  __reducerSchema("set_env_var", SetEnvVarReducer),
  __reducerSchema("unregister_player", UnregisterPlayerReducer),
  __reducerSchema("unstable_manual_register_override_players", UnstableManualRegisterOverridePlayersReducer),
  __reducerSchema("unstable_match_chat_message", UnstableMatchChatMessageReducer),
  __reducerSchema("unstable_raw_server_config_update_maps", UnstableRawServerConfigUpdateMapsReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
  __procedureSchema("login_as_server", LoginAsServerProcedure.params, LoginAsServerProcedure.returnType),
  __procedureSchema("match_round_replay", MatchRoundReplayProcedure.params, MatchRoundReplayProcedure.returnType),
  __procedureSchema("node_leaderboard_input", NodeLeaderboardInputProcedure.params, NodeLeaderboardInputProcedure.returnType),
  __procedureSchema("node_leaderboard_input_finalize", NodeLeaderboardInputFinalizeProcedure.params, NodeLeaderboardInputFinalizeProcedure.returnType),
  __procedureSchema("node_leaderboard_output", NodeLeaderboardOutputProcedure.params, NodeLeaderboardOutputProcedure.returnType),
  __procedureSchema("node_leaderboard_output_raw", NodeLeaderboardOutputRawProcedure.params, NodeLeaderboardOutputRawProcedure.returnType),
  __procedureSchema("post_round_replay", PostRoundReplayProcedure.params, PostRoundReplayProcedure.returnType),
  __procedureSchema("test_node_permitted_players_input", TestNodePermittedPlayersInputProcedure.params, TestNodePermittedPlayersInputProcedure.returnType),
  __procedureSchema("unstable_competition", UnstableCompetitionProcedure.params, UnstableCompetitionProcedure.returnType),
);

type __SchemaWithTableAccessorAliases = Omit<typeof tablesSchema.schemaType, "tables"> & {
  tables: typeof tablesSchema.schemaType.tables & {
    /** @deprecated Use `eventRawServerMethod` instead. This alias will be removed in the next major version. */
    readonly "event_raw_server_method": Omit<typeof tablesSchema.schemaType.tables["eventRawServerMethod"], "accessorName"> & { readonly accessorName: "event_raw_server_method" };
    /** @deprecated Use `eventRawServerState` instead. This alias will be removed in the next major version. */
    readonly "event_raw_server_state": Omit<typeof tablesSchema.schemaType.tables["eventRawServerState"], "accessorName"> & { readonly accessorName: "event_raw_server_state" };
    /** @deprecated Use `tabMatch` instead. This alias will be removed in the next major version. */
    readonly "tab_match": Omit<typeof tablesSchema.schemaType.tables["tabMatch"], "accessorName"> & { readonly accessorName: "tab_match" };
    /** @deprecated Use `tabMatchChat` instead. This alias will be removed in the next major version. */
    readonly "tab_match_chat": Omit<typeof tablesSchema.schemaType.tables["tabMatchChat"], "accessorName"> & { readonly accessorName: "tab_match_chat" };
    /** @deprecated Use `tabMatchRoundPlayer` instead. This alias will be removed in the next major version. */
    readonly "tab_match_round_player": Omit<typeof tablesSchema.schemaType.tables["tabMatchRoundPlayer"], "accessorName"> & { readonly accessorName: "tab_match_round_player" };
    /** @deprecated Use `tabMatchRoundPlayerExt` instead. This alias will be removed in the next major version. */
    readonly "tab_match_round_player_ext": Omit<typeof tablesSchema.schemaType.tables["tabMatchRoundPlayerExt"], "accessorName"> & { readonly accessorName: "tab_match_round_player_ext" };
    /** @deprecated Use `tabRawServer` instead. This alias will be removed in the next major version. */
    readonly "tab_raw_server": Omit<typeof tablesSchema.schemaType.tables["tabRawServer"], "accessorName"> & { readonly accessorName: "tab_raw_server" };
    /** @deprecated Use `tabRawServerOccupation` instead. This alias will be removed in the next major version. */
    readonly "tab_raw_server_occupation": Omit<typeof tablesSchema.schemaType.tables["tabRawServerOccupation"], "accessorName"> & { readonly accessorName: "tab_raw_server_occupation" };
    /** @deprecated Use `tabRawServerPlayer` instead. This alias will be removed in the next major version. */
    readonly "tab_raw_server_player": Omit<typeof tablesSchema.schemaType.tables["tabRawServerPlayer"], "accessorName"> & { readonly accessorName: "tab_raw_server_player" };
    /** @deprecated Use `tabRegisterationPlayer` instead. This alias will be removed in the next major version. */
    readonly "tab_registeration_player": Omit<typeof tablesSchema.schemaType.tables["tabRegisterationPlayer"], "accessorName"> & { readonly accessorName: "tab_registeration_player" };
    /** @deprecated Use `tabRegistration` instead. This alias will be removed in the next major version. */
    readonly "tab_registration": Omit<typeof tablesSchema.schemaType.tables["tabRegistration"], "accessorName"> & { readonly accessorName: "tab_registration" };
    /** @deprecated Use `tabUser` instead. This alias will be removed in the next major version. */
    readonly "tab_user": Omit<typeof tablesSchema.schemaType.tables["tabUser"], "accessorName"> & { readonly accessorName: "tab_user" };
    /** @deprecated Use `competitionAvailableServerPool` instead. This alias will be removed in the next major version. */
    readonly "competition_available_server_pool": Omit<typeof tablesSchema.schemaType.tables["competitionAvailableServerPool"], "accessorName"> & { readonly accessorName: "competition_available_server_pool" };
    /** @deprecated Use `matchState` instead. This alias will be removed in the next major version. */
    readonly "match_state": Omit<typeof tablesSchema.schemaType.tables["matchState"], "accessorName"> & { readonly accessorName: "match_state" };
    /** @deprecated Use `myNodePositions` instead. This alias will be removed in the next major version. */
    readonly "my_node_positions": Omit<typeof tablesSchema.schemaType.tables["myNodePositions"], "accessorName"> & { readonly accessorName: "my_node_positions" };
    /** @deprecated Use `myProjects` instead. This alias will be removed in the next major version. */
    readonly "my_projects": Omit<typeof tablesSchema.schemaType.tables["myProjects"], "accessorName"> & { readonly accessorName: "my_projects" };
    /** @deprecated Use `myUser` instead. This alias will be removed in the next major version. */
    readonly "my_user": Omit<typeof tablesSchema.schemaType.tables["myUser"], "accessorName"> & { readonly accessorName: "my_user" };
    /** @deprecated Use `projectCompetitionDescendants` instead. This alias will be removed in the next major version. */
    readonly "project_competition_descendants": Omit<typeof tablesSchema.schemaType.tables["projectCompetitionDescendants"], "accessorName"> & { readonly accessorName: "project_competition_descendants" };
    /** @deprecated Use `rawServerPermittedPlayers` instead. This alias will be removed in the next major version. */
    readonly "raw_server_permitted_players": Omit<typeof tablesSchema.schemaType.tables["rawServerPermittedPlayers"], "accessorName"> & { readonly accessorName: "raw_server_permitted_players" };
    /** @deprecated Use `rawServerPlayerDestination` instead. This alias will be removed in the next major version. */
    readonly "raw_server_player_destination": Omit<typeof tablesSchema.schemaType.tables["rawServerPlayerDestination"], "accessorName"> & { readonly accessorName: "raw_server_player_destination" };
    /** @deprecated Use `unstableCompetitionConnection` instead. This alias will be removed in the next major version. */
    readonly "unstable_competition_connection": Omit<typeof tablesSchema.schemaType.tables["unstableCompetitionConnection"], "accessorName"> & { readonly accessorName: "unstable_competition_connection" };
  };
};

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.10.1" as const,
  },
  tables: tablesSchema.schemaType.tables as __SchemaWithTableAccessorAliases["tables"],
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  __SchemaWithTableAccessorAliases,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

const tableAccessorAliases = {
  "event_raw_server_method": "eventRawServerMethod",
  "event_raw_server_state": "eventRawServerState",
  "tab_match": "tabMatch",
  "tab_match_chat": "tabMatchChat",
  "tab_match_round_player": "tabMatchRoundPlayer",
  "tab_match_round_player_ext": "tabMatchRoundPlayerExt",
  "tab_raw_server": "tabRawServer",
  "tab_raw_server_occupation": "tabRawServerOccupation",
  "tab_raw_server_player": "tabRawServerPlayer",
  "tab_registeration_player": "tabRegisterationPlayer",
  "tab_registration": "tabRegistration",
  "tab_user": "tabUser",
  "competition_available_server_pool": "competitionAvailableServerPool",
  "match_state": "matchState",
  "my_node_positions": "myNodePositions",
  "my_projects": "myProjects",
  "my_user": "myUser",
  "project_competition_descendants": "projectCompetitionDescendants",
  "raw_server_permitted_players": "rawServerPermittedPlayers",
  "raw_server_player_destination": "rawServerPlayerDestination",
  "unstable_competition_connection": "unstableCompetitionConnection",
} as const;

function __withTableAccessorAliases<T extends object>(target: T, freeze = false): T {
  const out = Object.create(Object.getPrototypeOf(target)) as T & Record<string, unknown>;
  Object.defineProperties(out, Object.getOwnPropertyDescriptors(target));
  for (const [deprecatedAccessor, targetAccessor] of Object.entries(tableAccessorAliases)) {
    if (deprecatedAccessor in out) {
      continue;
    }
    Object.defineProperty(out, deprecatedAccessor, {
      enumerable: true,
      configurable: false,
      get: () => out[targetAccessor],
    });
  }
  return freeze ? Object.freeze(out) : out;
}

type __DbViewBase = __DbConnectionImpl<typeof REMOTE_MODULE>["db"];
export type DbView = __DbViewBase & {
  /** @deprecated Use `eventRawServerMethod` instead. This alias will be removed in the next major version. */
  readonly "event_raw_server_method": __DbViewBase["eventRawServerMethod"];
  /** @deprecated Use `eventRawServerState` instead. This alias will be removed in the next major version. */
  readonly "event_raw_server_state": __DbViewBase["eventRawServerState"];
  /** @deprecated Use `tabMatch` instead. This alias will be removed in the next major version. */
  readonly "tab_match": __DbViewBase["tabMatch"];
  /** @deprecated Use `tabMatchChat` instead. This alias will be removed in the next major version. */
  readonly "tab_match_chat": __DbViewBase["tabMatchChat"];
  /** @deprecated Use `tabMatchRoundPlayer` instead. This alias will be removed in the next major version. */
  readonly "tab_match_round_player": __DbViewBase["tabMatchRoundPlayer"];
  /** @deprecated Use `tabMatchRoundPlayerExt` instead. This alias will be removed in the next major version. */
  readonly "tab_match_round_player_ext": __DbViewBase["tabMatchRoundPlayerExt"];
  /** @deprecated Use `tabRawServer` instead. This alias will be removed in the next major version. */
  readonly "tab_raw_server": __DbViewBase["tabRawServer"];
  /** @deprecated Use `tabRawServerOccupation` instead. This alias will be removed in the next major version. */
  readonly "tab_raw_server_occupation": __DbViewBase["tabRawServerOccupation"];
  /** @deprecated Use `tabRawServerPlayer` instead. This alias will be removed in the next major version. */
  readonly "tab_raw_server_player": __DbViewBase["tabRawServerPlayer"];
  /** @deprecated Use `tabRegisterationPlayer` instead. This alias will be removed in the next major version. */
  readonly "tab_registeration_player": __DbViewBase["tabRegisterationPlayer"];
  /** @deprecated Use `tabRegistration` instead. This alias will be removed in the next major version. */
  readonly "tab_registration": __DbViewBase["tabRegistration"];
  /** @deprecated Use `tabUser` instead. This alias will be removed in the next major version. */
  readonly "tab_user": __DbViewBase["tabUser"];
  /** @deprecated Use `competitionAvailableServerPool` instead. This alias will be removed in the next major version. */
  readonly "competition_available_server_pool": __DbViewBase["competitionAvailableServerPool"];
  /** @deprecated Use `matchState` instead. This alias will be removed in the next major version. */
  readonly "match_state": __DbViewBase["matchState"];
  /** @deprecated Use `myNodePositions` instead. This alias will be removed in the next major version. */
  readonly "my_node_positions": __DbViewBase["myNodePositions"];
  /** @deprecated Use `myProjects` instead. This alias will be removed in the next major version. */
  readonly "my_projects": __DbViewBase["myProjects"];
  /** @deprecated Use `myUser` instead. This alias will be removed in the next major version. */
  readonly "my_user": __DbViewBase["myUser"];
  /** @deprecated Use `projectCompetitionDescendants` instead. This alias will be removed in the next major version. */
  readonly "project_competition_descendants": __DbViewBase["projectCompetitionDescendants"];
  /** @deprecated Use `rawServerPermittedPlayers` instead. This alias will be removed in the next major version. */
  readonly "raw_server_permitted_players": __DbViewBase["rawServerPermittedPlayers"];
  /** @deprecated Use `rawServerPlayerDestination` instead. This alias will be removed in the next major version. */
  readonly "raw_server_player_destination": __DbViewBase["rawServerPlayerDestination"];
  /** @deprecated Use `unstableCompetitionConnection` instead. This alias will be removed in the next major version. */
  readonly "unstable_competition_connection": __DbViewBase["unstableCompetitionConnection"];
};

type __TablesBase = __QueryBuilder<typeof tablesSchema.schemaType>;
export type Tables = __TablesBase & {
  /** @deprecated Use `eventRawServerMethod` instead. This alias will be removed in the next major version. */
  readonly "event_raw_server_method": __TablesBase["eventRawServerMethod"];
  /** @deprecated Use `eventRawServerState` instead. This alias will be removed in the next major version. */
  readonly "event_raw_server_state": __TablesBase["eventRawServerState"];
  /** @deprecated Use `tabMatch` instead. This alias will be removed in the next major version. */
  readonly "tab_match": __TablesBase["tabMatch"];
  /** @deprecated Use `tabMatchChat` instead. This alias will be removed in the next major version. */
  readonly "tab_match_chat": __TablesBase["tabMatchChat"];
  /** @deprecated Use `tabMatchRoundPlayer` instead. This alias will be removed in the next major version. */
  readonly "tab_match_round_player": __TablesBase["tabMatchRoundPlayer"];
  /** @deprecated Use `tabMatchRoundPlayerExt` instead. This alias will be removed in the next major version. */
  readonly "tab_match_round_player_ext": __TablesBase["tabMatchRoundPlayerExt"];
  /** @deprecated Use `tabRawServer` instead. This alias will be removed in the next major version. */
  readonly "tab_raw_server": __TablesBase["tabRawServer"];
  /** @deprecated Use `tabRawServerOccupation` instead. This alias will be removed in the next major version. */
  readonly "tab_raw_server_occupation": __TablesBase["tabRawServerOccupation"];
  /** @deprecated Use `tabRawServerPlayer` instead. This alias will be removed in the next major version. */
  readonly "tab_raw_server_player": __TablesBase["tabRawServerPlayer"];
  /** @deprecated Use `tabRegisterationPlayer` instead. This alias will be removed in the next major version. */
  readonly "tab_registeration_player": __TablesBase["tabRegisterationPlayer"];
  /** @deprecated Use `tabRegistration` instead. This alias will be removed in the next major version. */
  readonly "tab_registration": __TablesBase["tabRegistration"];
  /** @deprecated Use `tabUser` instead. This alias will be removed in the next major version. */
  readonly "tab_user": __TablesBase["tabUser"];
  /** @deprecated Use `competitionAvailableServerPool` instead. This alias will be removed in the next major version. */
  readonly "competition_available_server_pool": __TablesBase["competitionAvailableServerPool"];
  /** @deprecated Use `matchState` instead. This alias will be removed in the next major version. */
  readonly "match_state": __TablesBase["matchState"];
  /** @deprecated Use `myNodePositions` instead. This alias will be removed in the next major version. */
  readonly "my_node_positions": __TablesBase["myNodePositions"];
  /** @deprecated Use `myProjects` instead. This alias will be removed in the next major version. */
  readonly "my_projects": __TablesBase["myProjects"];
  /** @deprecated Use `myUser` instead. This alias will be removed in the next major version. */
  readonly "my_user": __TablesBase["myUser"];
  /** @deprecated Use `projectCompetitionDescendants` instead. This alias will be removed in the next major version. */
  readonly "project_competition_descendants": __TablesBase["projectCompetitionDescendants"];
  /** @deprecated Use `rawServerPermittedPlayers` instead. This alias will be removed in the next major version. */
  readonly "raw_server_permitted_players": __TablesBase["rawServerPermittedPlayers"];
  /** @deprecated Use `rawServerPlayerDestination` instead. This alias will be removed in the next major version. */
  readonly "raw_server_player_destination": __TablesBase["rawServerPlayerDestination"];
  /** @deprecated Use `unstableCompetitionConnection` instead. This alias will be removed in the next major version. */
  readonly "unstable_competition_connection": __TablesBase["unstableCompetitionConnection"];
};

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
const tablesBase: __TablesBase = __makeQueryBuilder(tablesSchema.schemaType);
export const tables: Tables = __withTableAccessorAliases(tablesBase, true) as Tables;

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = Omit<__EventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = Omit<__ReducerEventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = Omit<__SubscriptionEventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for error events. */
export type ErrorContext = Omit<__ErrorContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  declare db: DbView;

  constructor(config: __DbConnectionConfig<typeof REMOTE_MODULE>) {
    super(config);
    this.db = __withTableAccessorAliases(this.db) as DbView;
  }

  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

