// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.5 (commit d60138999206c06c776829072f46b5d1c1101f7e).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import CompetitionConnectionDataUpdateReducer from "./competition_connection_data_update_reducer";
import CompetitionCreateReducer from "./competition_create_reducer";
import CompetitionEditNameReducer from "./competition_edit_name_reducer";
import CompetitionNodePositionUpdateReducer from "./competition_node_position_update_reducer";
import CompetitionNodePositionsUpdateReducer from "./competition_node_positions_update_reducer";
import CompetitionTemplateCreateReducer from "./competition_template_create_reducer";
import ConnectionCreateReducer from "./connection_create_reducer";
import CreateProjectReducer from "./create_project_reducer";
import CreateTeamReducer from "./create_team_reducer";
import LendRawServerReducer from "./lend_raw_server_reducer";
import MatchAssignServerReducer from "./match_assign_server_reducer";
import MatchConfiguredReducer from "./match_configured_reducer";
import MatchCreateReducer from "./match_create_reducer";
import MatchDeleteReducer from "./match_delete_reducer";
import MatchSetPreparationReducer from "./match_set_preparation_reducer";
import MatchTemplateCreateReducer from "./match_template_create_reducer";
import MatchTryStartReducer from "./match_try_start_reducer";
import MatchUpdateConfigReducer from "./match_update_config_reducer";
import MatchUpdatePreConfigReducer from "./match_update_pre_config_reducer";
import MemberAddReducer from "./member_add_reducer";
import MemberAssignPermissionReducer from "./member_assign_permission_reducer";
import MemberRemoveReducer from "./member_remove_reducer";
import PortalCreateReducer from "./portal_create_reducer";
import PostEventReducer from "./post_event_reducer";
import PostRecordReducer from "./post_record_reducer";
import ProjectEditDatesReducer from "./project_edit_dates_reducer";
import ProjectEditDescriptionReducer from "./project_edit_description_reducer";
import ProjectEditNameReducer from "./project_edit_name_reducer";
import ProjectUpdateStatusReducer from "./project_update_status_reducer";
import RawServerVerifyReducer from "./raw_server_verify_reducer";
import RegisterPlayerReducer from "./register_player_reducer";
import RegistrationConfiguredReducer from "./registration_configured_reducer";
import RegistrationCreateReducer from "./registration_create_reducer";
import RegistrationEndReducer from "./registration_end_reducer";
import RegistrationStartReducer from "./registration_start_reducer";
import RegistrationTemplateCreateReducer from "./registration_template_create_reducer";
import RevokeRawServerReducer from "./revoke_raw_server_reducer";
import RoleAssignPermissionReducer from "./role_assign_permission_reducer";
import RoleCreateReducer from "./role_create_reducer";
import RoleMemberAssignReducer from "./role_member_assign_reducer";
import RoleMemberRemoveReducer from "./role_member_remove_reducer";
import RoleRemoveReducer from "./role_remove_reducer";
import ScheduleConfiguredReducer from "./schedule_configured_reducer";
import ScheduleCreateReducer from "./schedule_create_reducer";
import ScheduleTryRunReducer from "./schedule_try_run_reducer";
import ServerMethodCallReducer from "./server_method_call_reducer";
import ServerMethodResponseReducer from "./server_method_response_reducer";
import SetEnvVarReducer from "./set_env_var_reducer";
import UnregisterPlayerReducer from "./unregister_player_reducer";

// Import all procedure arg schemas
import * as LoginAsServerProcedure from "./login_as_server_procedure";
import * as LoginAsWorkerProcedure from "./login_as_worker_procedure";
import * as PostRoundReplayProcedure from "./post_round_replay_procedure";

// Import all table schema definitions
import ComeptitionSchedulesRow from "./comeptition_schedules_table";
import CompetitionRow from "./competition_table";
import CompetitionAvailableServerPoolRow from "./competition_available_server_pool_table";
import CompetitionConnectionRow from "./competition_connection_table";
import CompetitionConnectionDataRow from "./competition_connection_data_table";
import CompetitionNodePositionRow from "./competition_node_position_table";
import CompetitionRecordRow from "./competition_record_table";
import MapRecordRow from "./map_record_table";
import MatchLeaderboardRow from "./match_leaderboard_table";
import MatchRecordRow from "./match_record_table";
import MatchRoundRow from "./match_round_table";
import MatchRoundExtRow from "./match_round_ext_table";
import MatchStateRow from "./match_state_table";
import MyJobsRow from "./my_jobs_table";
import MyMatchTemplateRow from "./my_match_template_table";
import MyProjectRow from "./my_project_table";
import MyUserRow from "./my_user_table";
import ProjectRow from "./project_table";
import RawServerAllowedPlayersRow from "./raw_server_allowed_players_table";
import RawServerConfigRow from "./raw_server_config_table";
import RawServerCurrentPlayersRow from "./raw_server_current_players_table";
import RawServerMethodCallRow from "./raw_server_method_call_table";
import RegistrationPlayerRow from "./registration_player_table";
import ThisRawServerRow from "./this_raw_server_table";
import TmMapRecordRow from "./tm_map_record_table";
import UserAvailableServerPoolRow from "./user_available_server_pool_table";
import UserRawServerPoolRow from "./user_raw_server_pool_table";
import UserRawServerPoolUnverifiedRow from "./user_raw_server_pool_unverified_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  tm_map_record: __table({
    name: 'tm_map_record',
    indexes: [
      { accessor: 'id', name: 'tm_map_record_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'record_id', name: 'tm_map_record_map_uid_account_id_idx_btree', algorithm: 'btree', columns: [
        'mapUid',
        'accountId',
      ] },
    ],
    constraints: [
      { name: 'tm_map_record_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TmMapRecordRow),
  comeptition_schedules: __table({
    name: 'comeptition_schedules',
    indexes: [
    ],
    constraints: [
    ],
  }, ComeptitionSchedulesRow),
  competition: __table({
    name: 'competition',
    indexes: [
    ],
    constraints: [
    ],
  }, CompetitionRow),
  competition_available_server_pool: __table({
    name: 'competition_available_server_pool',
    indexes: [
    ],
    constraints: [
    ],
  }, CompetitionAvailableServerPoolRow),
  competition_connection: __table({
    name: 'competition_connection',
    indexes: [
    ],
    constraints: [
    ],
  }, CompetitionConnectionRow),
  competition_connection_data: __table({
    name: 'competition_connection_data',
    indexes: [
    ],
    constraints: [
    ],
  }, CompetitionConnectionDataRow),
  competition_node_position: __table({
    name: 'competition_node_position',
    indexes: [
    ],
    constraints: [
    ],
  }, CompetitionNodePositionRow),
  competition_record: __table({
    name: 'competition_record',
    indexes: [
    ],
    constraints: [
    ],
  }, CompetitionRecordRow),
  map_record: __table({
    name: 'map_record',
    indexes: [
    ],
    constraints: [
    ],
  }, MapRecordRow),
  match_leaderboard: __table({
    name: 'match_leaderboard',
    indexes: [
    ],
    constraints: [
    ],
  }, MatchLeaderboardRow),
  match_record: __table({
    name: 'match_record',
    indexes: [
    ],
    constraints: [
    ],
  }, MatchRecordRow),
  match_round: __table({
    name: 'match_round',
    indexes: [
    ],
    constraints: [
    ],
  }, MatchRoundRow),
  match_round_ext: __table({
    name: 'match_round_ext',
    indexes: [
    ],
    constraints: [
    ],
  }, MatchRoundExtRow),
  match_state: __table({
    name: 'match_state',
    indexes: [
    ],
    constraints: [
    ],
  }, MatchStateRow),
  my_jobs: __table({
    name: 'my_jobs',
    indexes: [
    ],
    constraints: [
    ],
  }, MyJobsRow),
  my_match_template: __table({
    name: 'my_match_template',
    indexes: [
    ],
    constraints: [
    ],
  }, MyMatchTemplateRow),
  my_project: __table({
    name: 'my_project',
    indexes: [
    ],
    constraints: [
    ],
  }, MyProjectRow),
  my_user: __table({
    name: 'my_user',
    indexes: [
    ],
    constraints: [
    ],
  }, MyUserRow),
  project: __table({
    name: 'project',
    indexes: [
    ],
    constraints: [
    ],
  }, ProjectRow),
  raw_server_allowed_players: __table({
    name: 'raw_server_allowed_players',
    indexes: [
    ],
    constraints: [
    ],
  }, RawServerAllowedPlayersRow),
  raw_server_config: __table({
    name: 'raw_server_config',
    indexes: [
    ],
    constraints: [
    ],
  }, RawServerConfigRow),
  raw_server_current_players: __table({
    name: 'raw_server_current_players',
    indexes: [
    ],
    constraints: [
    ],
  }, RawServerCurrentPlayersRow),
  raw_server_method_call: __table({
    name: 'raw_server_method_call',
    indexes: [
    ],
    constraints: [
    ],
  }, RawServerMethodCallRow),
  registration_player: __table({
    name: 'registration_player',
    indexes: [
    ],
    constraints: [
    ],
  }, RegistrationPlayerRow),
  this_raw_server: __table({
    name: 'this_raw_server',
    indexes: [
    ],
    constraints: [
    ],
  }, ThisRawServerRow),
  user_available_server_pool: __table({
    name: 'user_available_server_pool',
    indexes: [
    ],
    constraints: [
    ],
  }, UserAvailableServerPoolRow),
  user_raw_server_pool: __table({
    name: 'user_raw_server_pool',
    indexes: [
    ],
    constraints: [
    ],
  }, UserRawServerPoolRow),
  user_raw_server_pool_unverified: __table({
    name: 'user_raw_server_pool_unverified',
    indexes: [
    ],
    constraints: [
    ],
  }, UserRawServerPoolUnverifiedRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("competition_connection_data_update", CompetitionConnectionDataUpdateReducer),
  __reducerSchema("competition_create", CompetitionCreateReducer),
  __reducerSchema("competition_edit_name", CompetitionEditNameReducer),
  __reducerSchema("competition_node_position_update", CompetitionNodePositionUpdateReducer),
  __reducerSchema("competition_node_positions_update", CompetitionNodePositionsUpdateReducer),
  __reducerSchema("competition_template_create", CompetitionTemplateCreateReducer),
  __reducerSchema("connection_create", ConnectionCreateReducer),
  __reducerSchema("create_project", CreateProjectReducer),
  __reducerSchema("create_team", CreateTeamReducer),
  __reducerSchema("lend_raw_server", LendRawServerReducer),
  __reducerSchema("match_assign_server", MatchAssignServerReducer),
  __reducerSchema("match_configured", MatchConfiguredReducer),
  __reducerSchema("match_create", MatchCreateReducer),
  __reducerSchema("match_delete", MatchDeleteReducer),
  __reducerSchema("match_set_preparation", MatchSetPreparationReducer),
  __reducerSchema("match_template_create", MatchTemplateCreateReducer),
  __reducerSchema("match_try_start", MatchTryStartReducer),
  __reducerSchema("match_update_config", MatchUpdateConfigReducer),
  __reducerSchema("match_update_pre_config", MatchUpdatePreConfigReducer),
  __reducerSchema("member_add", MemberAddReducer),
  __reducerSchema("member_assign_permission", MemberAssignPermissionReducer),
  __reducerSchema("member_remove", MemberRemoveReducer),
  __reducerSchema("portal_create", PortalCreateReducer),
  __reducerSchema("post_event", PostEventReducer),
  __reducerSchema("post_record", PostRecordReducer),
  __reducerSchema("project_edit_dates", ProjectEditDatesReducer),
  __reducerSchema("project_edit_description", ProjectEditDescriptionReducer),
  __reducerSchema("project_edit_name", ProjectEditNameReducer),
  __reducerSchema("project_update_status", ProjectUpdateStatusReducer),
  __reducerSchema("raw_server_verify", RawServerVerifyReducer),
  __reducerSchema("register_player", RegisterPlayerReducer),
  __reducerSchema("registration_configured", RegistrationConfiguredReducer),
  __reducerSchema("registration_create", RegistrationCreateReducer),
  __reducerSchema("registration_end", RegistrationEndReducer),
  __reducerSchema("registration_start", RegistrationStartReducer),
  __reducerSchema("registration_template_create", RegistrationTemplateCreateReducer),
  __reducerSchema("revoke_raw_server", RevokeRawServerReducer),
  __reducerSchema("role_assign_permission", RoleAssignPermissionReducer),
  __reducerSchema("role_create", RoleCreateReducer),
  __reducerSchema("role_member_assign", RoleMemberAssignReducer),
  __reducerSchema("role_member_remove", RoleMemberRemoveReducer),
  __reducerSchema("role_remove", RoleRemoveReducer),
  __reducerSchema("schedule_configured", ScheduleConfiguredReducer),
  __reducerSchema("schedule_create", ScheduleCreateReducer),
  __reducerSchema("schedule_try_run", ScheduleTryRunReducer),
  __reducerSchema("server_method_call", ServerMethodCallReducer),
  __reducerSchema("server_method_response", ServerMethodResponseReducer),
  __reducerSchema("set_env_var", SetEnvVarReducer),
  __reducerSchema("unregister_player", UnregisterPlayerReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
  __procedureSchema("login_as_server", LoginAsServerProcedure.params, LoginAsServerProcedure.returnType),
  __procedureSchema("login_as_worker", LoginAsWorkerProcedure.params, LoginAsWorkerProcedure.returnType),
  __procedureSchema("post_round_replay", PostRoundReplayProcedure.params, PostRoundReplayProcedure.returnType),
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.0.5" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

