// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  NodeHandle,
  ConnectionKind,
  ConnectionStatus,
} from "./types";


export default __t.row({
  id: __t.u32(),
  competitionId: __t.u32().name("competition_id"),
  get origin() {
    return NodeHandle;
  },
  get target() {
    return NodeHandle;
  },
  get kind() {
    return ConnectionKind;
  },
  get status() {
    return ConnectionStatus;
  },
});
