// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  MatchStatus,
} from "./types";


export default __t.row({
  name: __t.string(),
  id: __t.u32().primaryKey(),
  parentId: __t.u32().name("parent_id"),
  preConfig: __t.u32().name("pre_config"),
  config: __t.u32(),
  get status() {
    return MatchStatus;
  },
  autoProvisionServer: __t.bool().name("auto_provision_server"),
  open: __t.bool(),
  template: __t.bool(),
});
