// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  ProjectKind,
  ProjectStatus,
} from "./types";


export default __t.row({
  name: __t.string(),
  description: __t.string(),
  startingAt: __t.timestamp().name("starting_at"),
  endingAt: __t.timestamp().name("ending_at"),
  userId: __t.u32().name("user_id"),
  id: __t.u32(),
  verified: __t.bool(),
  get kind() {
    return ProjectKind;
  },
  get status() {
    return ProjectStatus;
  },
  rootCompetition: __t.u32().name("root_competition"),
});
