// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  MethodCall,
} from "./types";


export default __t.row({
  id: __t.u32(),
  serverId: __t.u32().name("server_id"),
  userId: __t.u32().name("user_id"),
  timestamp: __t.timestamp(),
  get call() {
    return MethodCall;
  },
});
