// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  PlayerAction,
} from "./types";


export default __t.row({
  get roundActions() {
    return __t.array(PlayerAction).name("round_actions");
  },
  id: __t.u32(),
  matchId: __t.u32().name("match_id"),
  round: __t.u16(),
});
